### ISSUE TITLE
ActionController::UrlGenerationError when using route namespace constraint

### ISSUE THREAD

**Issue by jwilliams-handy** [rspec/rspec-rails#1996] opened 2018-05-23 22:38 UTC
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.1.8p440
Rails version: 4.0.13
Rspec version: 3.7

## Observed behaviour

I am adding a new version to an existing API. I have added a constraint to a `namespace` in my routes file. The route evaluates fine when hitting the route via an http call. However it is failing on every single controller spec that is written in the test suite. If I do a spec of `type: :request` they seem to be passing but there are lots of controller specs and I wouldn't like to convert them all over at this moment.

The errors all look like this:

```
ActionController::UrlGenerationError:
       No route matches {:action=>"create", :controller=>"api/v1/some_object"}
```

original:

```
  namespace :api, constraints: { format: :json } do
    ["", "something"].each do |s|
      scope s, as: s do
        namespace :v1 do
          get "/data" => "base#data"
          etc.........
      end
    end
  end
```

I added a simple constraint on the namespace line to allow for filtering down requests from 2 versions.

`namespace :v3, path: ":api_version", constraints: { api_version: /v[12]/ } do`

## Expected behaviour

I expect the routes to be found as the constraint evaluates properly over any other request.

**Comment by JonRowe** [comment] 2018-05-24 20:14
We are dependant on Rails to resolve our routes, it looks like your route isn't matching because controllers know nothing about json format, if you pass `format: :json` it should work. Note controller specs are deprecated in Rails 5 so converting them will not be a waste of time :p

**Comment by jwilliams-handy** [comment] 2018-05-24 20:21
@JonRowe that `format: :json` piece works fine without the constraint with the controller specs. tried passing it along to give it a shot and get the same error.

I've gravitated towards the opinion of moving to request specs but was hoping for a bridging solution beforehand

**Comment by JonRowe** [comment] 2018-05-24 20:22
Unfortunately you need to pass all the bits Rails would pass through to match the route, I think this is one of the reasons why they got deprecated, you have to know too much about them!

**Comment by samphippen** [comment] 2018-06-22 14:29
Thanks for the issue. We need a little more detail to be able to reproduce this.

Could you please provide us with a rails app that we can clone that demonstrates the issue. Specifically it'd be great if

1)  you could `rails new` an application and commit
2) make all the changes necessary to reproduce the issue and commit

then, provide us with a description of how to clone your application and reproduce the issue.

Thanks :)

**Comment by pirj** [comment] 2020-03-20 23:08
Closing as stalled.

**Closed by pirj** 2020-03-20 23:08 UTC
Labels: Needs reproduction case
