### ISSUE TITLE
Route helpers are not defined in helper and view specs

### ISSUE THREAD

**Issue by beydogan** [rspec/rspec-rails#1644] opened 2016-06-23 07:56 UTC
I've just upgraded my Rails version from **4.2.6** to **5.0.0.rc1** and using RSpec version **3.5.0.beta4**(was 3.3.3).

Problem is; I have a method which calls `root_path` in my helper and paths are not defined in helper specs. Issue started after version upgrade.

I'm getting the following error when I run my helper spec;

```ruby
NoMethodError: undefined method `root_path' for #<#<Class:0x00000002749080>:0x00000011f3e650>
```

I've tried to add following line to my helper;

```ruby
include Rails.application.routes.url_helpers
```

But now error is the following;

```ruby
NameError: undefined local variable or method `default_url_options' for #<#<Class:0x00000001efa550>:0x0000001784ccd8>
```

How can I define path helpers for helper specs or default_url_options?

**Comment by tirdadc** [comment] 2016-07-03 14:49
Same issue with Rails 5.0.0 and Rspec 3.5.0.

**Comment by samphippen** [comment] 2016-07-03 16:59
Thanks for the issue. We need a little more detail to be able to reproduce this.

Could you please provide us with a rails app that we can clone that demonstrates the issue. Specifically it'd be great if

1)  you could `rails new` an application and commit
2) make all the changes necessary to reproduce the issue and commit

then, provide us with a description of how to clone your application and reproduce the issue.

Thanks :)

**Comment by juno** [comment] 2016-07-04 14:03
Same here.
My problem has solved by removing `rails-controller-testing` gem from `Gemfile`.

**Comment by tirdadc** [comment] 2016-07-04 18:34
The issue has been mentioned there https://github.com/rails/rails-controller-testing/issues/24

**Comment by mrageh** [comment] 2016-07-05 01:49
@samphippen I've created a new rails app with an initial commit without `rails-controller-testing` gem and the url helpers work fine in both view/helper specs. 

After adding the `rails-controller-testing` the url helpers still work on both view/helper specs. 

I can push a repo up and maybe someone else can try to reproduce the issue?

Version info Rails 5.0.0, Rspec 3.5.0 and gem rails-controller-testing 0.1.1

**Comment by samphippen** [comment] 2016-07-05 09:14
@mrageh thanks for giving it a go. We test against a new vanilla rails app as part of RSpec Rails's test suite. If we can get a clean reproduction case, then I'll gladly take a look at the issue. For the moment we've not seen a rails app that can produce this issue, so we can't debug. I'm happy to take a look at this as soon as there's a reproduction case. I suspect we'll upstream this to rails also.

**Comment by juno** [comment] 2016-07-05 11:27
@mrageh

> After adding the rails-controller-testing the url helpers still work on both view/helper specs.
> 
> I can push a repo up and maybe someone else can try to reproduce the issue?

I created vanilla rails 5.0 app and investigated root cause by adding each gem from my Rails app's `Gemfile`.
At this time I suspect that there is something conflict between `rails-controller-testing` and [twitter/secureheaders](https://github.com/twitter/secureheaders).

## How to reproduce

Create vanilla Rails 5.0 app:

```console
$ rails -v
Rails 5.0.0
$ rails new experiment --skip-bundle --skip-test
$ cd experiment
```

Add `rspec-rails` and `rails-controller-testing` to `Gemfile`:

```ruby
group :development, :test do
  gem 'rspec-rails', '3.5.0'
end

group :test do
  gem 'rails-controller-testing', '0.1.1'
end
```

Install rspec-rails:

```console
$ bundle --path vendor/bundle
$ rails generate rspec:install
```

Define route:

```ruby
# config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
end
```

Add helper spec:

```ruby
# spec/helpers/application_helper_spec.rb
require 'rails_helper'

RSpec.describe ApplicationHelper, type: :helper do
  it 'has url helper' do
    p root_path
  end
end
```

Test finished without failures:

```console
$ rake
/Users/juno/.rbenv/versions/2.3.1/bin/ruby -I/Users/juno/src/experiment/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.5.0/lib:/Users/juno/src/experiment/vendor/bundle/ruby/2.3.0/gems/rspec-support-3.5.0/lib /Users/juno/src/experiment/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.5.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
/Users/juno/src/experiment/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /Users/juno/src/experiment/config/application.rb to limit the frameworks that will be loaded.
"/"
.

Finished in 0.00954 seconds (files took 4.17 seconds to load)
1 example, 0 failures
```

Add `secure_headers` to `Gemfile` and bundle it.

```ruby
gem 'secure_headers', '3.3.2'
```

Test has failed:

```console
$ rake
/Users/juno/.rbenv/versions/2.3.1/bin/ruby -I/Users/juno/src/experiment/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.5.0/lib:/Users/juno/src/experiment/vendor/bundle/ruby/2.3.0/gems/rspec-support-3.5.0/lib /Users/juno/src/experiment/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.5.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
/Users/juno/src/experiment/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /Users/juno/src/experiment/config/application.rb to limit the frameworks that will be loaded.
F

Failures:

  1) ApplicationHelper has url helper
     Failure/Error: p root_path

     NameError:
       undefined local variable or method `root_path' for #<RSpec::ExampleGroups::ApplicationHelper:0x007fd95f9608a8>
     # ./spec/helpers/application_helper_spec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 0.01303 seconds (files took 4.2 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/helpers/application_helper_spec.rb:4 # ApplicationHelper has url helper

/Users/juno/.rbenv/versions/2.3.1/bin/ruby -I/Users/juno/src/experiment/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.5.0/lib:/Users/juno/src/experiment/vendor/bundle/ruby/2.3.0/gems/rspec-support-3.5.0/lib /Users/juno/src/experiment/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.5.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

I confirmed this with secure_headers 2.5.2 (previous major release) and 3.3.2 (current release).
Unfortunately I have no time to find out the cause of this confliction...

@samphippen 
I hope this will be of some help.

**Comment by samphippen** [comment] 2016-07-05 11:40
I've pushed a demo app which reproduces this here: https://github.com/samphippen/demo_app_for_rspec_1644

**Comment by radar** [comment] 2016-07-20 23:52
Thanks for that app @samphippen. I tried reproducing it in my own app with just rspec-rails, and it _worked_. The difference between my app and yours was the addition of the `rails-controller-testing` gem:

```ruby
group :test do
    gem 'rails-controller-testing', '0.1.1'
end
```

If I comment these lines out in your app's `Gemfile`, then the issue goes away. I'll continue to investigate this and try to get to the bottom of what `rails-controller-testing` is doing.

**Comment by tjgrathwell** [comment] 2016-07-21 01:11
Interestingly, you can work around the problem by moving the gem's `require` to initialization time:

in Gemfile:
```
group :test do
  gem 'rails-controller-testing', require: false
end
```

in `config/initializers/rails_controller_testing.rb`(or whereever)
```
require 'rails-controller-testing' if Rails.env.test?
```

I don't know the exact mechanism why, but it works on my app (views in test can see helpers, rails-controller-testing features still work).

I would've thought you could achieve the same effect by putting the offending content from the gem into a Railtie with an initialize block, but that actually doesn't work.

**Comment by sgrif** [comment] 2016-08-11 18:44
This should be fixed upstream.

**Comment by samphippen** [comment] 2016-08-11 19:10
👍

**Closed by samphippen** 2016-08-11 19:10 UTC
Labels: Has reproduction case

**Comment by razvan-sv** [comment] 2019-09-26 09:27
This will probably help somebody. I spent so much time to track it down.

In a very old test I had this:
```ruby
before(:each) do
  routes.draw { get 'search' => 'warden#search' }
end
```
which caused helper tests to fail intermittently. 

Fixed by adding:
```ruby
  after do  
    Rails.application.reload_routes!
  end
```
