### ISSUE TITLE
Error while require rspec/rails

### ISSUE THREAD

**Issue by phsacramento** [rspec/rspec-rails#2132] opened 2019-05-21 23:35 UTC
Ruby version: 2.6.3
Rails version: 5.2.3
RSpec version: 3.8.2

```ruby
An error occurred while loading spec_helper.
Failure/Error: require 'rspec/rails'

FrozenError:
  can't modify frozen String
# ./spec/spec_helper.rb:9:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- action_view/test_case/test_helper
#   ./spec/spec_helper.rb:9:in `<top (required)>'
```
spec_helper.rb

```ruby
# frozen_string_literal: true
ENV['RAILS_ENV'] = 'test'

require 'simplecov'
SimpleCov.start('rails')

require File.expand_path('../config/environment', __dir__)

require 'rspec/rails'
require 'database_cleaner'
require 'shoulda/matchers'
require 'webmock/rspec'
require 'aasm/rspec'
require 'capybara/rails'
require 'selenium-webdriver'
require 'sidekiq/testing'
require 'pundit/matchers'

...
``` 

Gemfile

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'bootsnap', '>= 1.1.0', require: false
gem 'devise'
gem 'font-awesome-rails'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'rails', '~> 5.2.3'
gem 'rails-i18n', '~> 5.1'
gem 'sass-rails', '~> 5.0'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'
gem 'omniauth-linkedin-oauth2'
gem 'devise-i18n'
gem 'redis'
gem 'sidekiq'
gem 'pundit'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

group :development, :test do
  gem "letter_opener"
  gem 'annotate'
  gem 'brakeman', require: false
  gem 'byebug', platforms: %i(mri mingw x64_mingw)
  gem 'dotenv-rails', require: 'dotenv/rails-now'
  gem 'pry-rails'
  gem 'rspec-ontap', require: false
  gem 'rspec-rails', '~> 3.8'
  gem 'rubocop', require: false
  gem 'rubocop-performance'
  gem 'rubocop-rspec'
  gem 'rubycritic', require: false
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'vcr'
  gem 'webmock'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'capybara-email'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'geckodriver-helper'
  gem 'pundit-matchers', '~> 1.6.0'
  gem 'rails-controller-testing'
  gem 'rspec-sidekiq'
  gem 'selenium-webdriver'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
```

model_spec.rb

```ruby
# frozen_string_literal: true
require 'spec_helper'

RSpec.describe(Model, type: :model) do
  pending "add some examples to (or delete) #{__FILE__}"
end
```

**Comment by JonRowe** [comment] 2019-05-23 10:34
I tried to replicate this using your provided code, which I had to modify to add `aasm` to the Gemfile, and a fresh rails app and got nothing, from the look of the cause by explanation it appears you have a rails app configured to run test unit as well? So it's looking for there test helper.

Can you make sure your rails app either hasn't got test unit enabled, or has the appropriate test unit configuration to prevent that load error.

**Comment by phsacramento** [comment] 2019-05-23 18:46
@JonRowe I this a new project, exists only default suite.

**Comment by JonRowe** [comment] 2019-05-24 11:46
@phsacramento you still somehow have a difference between a `rails new` with this code. (Although like I said your code is slightly inaccurate). Regardless this is most likely a problem with your repo unless you can replicate it!

**Comment by JonRowe** [comment] 2019-05-29 21:08
Hi @phsacramento if you can make a new rails app (so only gems etc) with this config reproducing the issue and push it to a public repo, one of us will be able to take a look at where this is coming from, otherwise we'll have to close this.

**Comment by benoittgt** [comment] 2019-09-04 05:44
Closing becausereproduction case not provided.

**Closed by benoittgt** 2019-09-04 05:44 UTC
Labels: Needs reproduction case

**Comment by pirj** [comment] 2019-11-28 10:58
I've just recently had the same problem `cannot load such file -- action_view/test_case/test_helper`, but it seems normal, as it's just ignored.
