### ISSUE TITLE
Test pass for a folder but fail for all

### ISSUE THREAD

**Issue by ahangarha** [rspec/rspec-rails#2613] opened 2022-07-14 18:16 UTC
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 3.1.2
Rails version: 7
RSpec version:
```
RSpec 3.11
  - rspec-core 3.11.0
  - rspec-expectations 3.11.0
  - rspec-mocks 3.11.1
  - rspec-rails 6.0.0.rc1
  - rspec-support 3.11.0
```

## Observed behaviour

Several times I have experienced this issue that there is no consistency between running tests individually, in folder and as a whole. Before I had case of test passes when running all tests but fail if be run on individual tests. I don't have reference for that but now I have this case to present.

When we run `rspec` or `rspec spec` we have 2 failure (issue was maching dynamic date with hardcoded ones so not related to other parts) but running `rspec /spec/requests` or running the exact test file, test could pass without issue.

![image](https://user-images.githubusercontent.com/11241315/179052901-a29be896-10ab-4f88-b85f-7b75d2cfd48a.png)

## Expected behaviour

We should have consistency over the tests. In this case, it was good that we had failure when running `rspec` but before it was opposite which was very bad for CI/CD.

## Can you provide an example app?

I can share the code in two or three weeks or if needed, I can share the code privately till then.

**Comment by pirj** [comment] 2022-07-14 19:01
> I can share the code in two or three weeks or if needed

Please come back with a reproduction repository when you can share it.

Before that, I can suggest you to `rspec bisect`.

**Comment by JonRowe** [comment] 2022-07-17 08:29
This looks like a pretty normal test interdependency issue where you have some form of shared state which isn't being handled properly so it leaks between tests, in particular its probably a leaking database entry which is causing both the last record to be unexpected, and presumedly preventing an entry from being saved. As RSpec doesn't handle these (its usually something like database cleaner or Rails transactional test helpers) its not something we can fix on our end.

I'm closing this for now but feel free to re open if you find something in RSpec itself that could be improved.

**Closed by JonRowe** 2022-07-17 08:29 UTC
Labels: Needs reproduction case

**Comment by ahangarha** [comment] 2022-07-17 08:55
MHi
My initial thought was the same but what was causeing the test to fail was a simple mistake in checking date. That should fail in all death of testing.

I can share whole spec folder if it can help. I just dont know how to do it. A temporary repo? Zip file?

در ۱۷ ژوئیهٔ ۲۰۲۲ ۱۱:۲۹:۴۱ (GMT+03:00)، Jon Rowe ***@***.***> نوشت:

**Comment by JonRowe** [comment] 2022-07-17 09:27
Your best option is to run `rspec --bisect` to find the minimalist failing set of specs, then reduce those further until you narrow down the source of the interdependant failure. Likely that will be in your codebase, if its not please gist a small snippet or use our issue template to produce the issue in a clean rails app, we don't have the bandwidth to debug your project for you I'm afraid.
