### ISSUE TITLE
after `bundle exec rspec` spec/ schema_migrations table missing

### ISSUE THREAD

**Issue by oncelife** [rspec/rspec-rails#1494] opened 2015-11-24 03:28 UTC
rspec-rails (3.2.1)
rspec (3.2.0)
rails (4.2.1)

i'm really confused.

**Comment by samphippen** [comment] 2015-11-29 22:59
I could not reproduce this. @oncelife can you provide a url to a git repo which contains a rails app that contains two commits:

* First commit is just the result of `rails g mytestapp`
* Second commit is all the changes necessary to reproduce this bug.

Then, give us some commands to run or similar to show the bug appearing. I'm happy to help you fix this, but I need to be able to reproduce this first. :smile:

**Comment by JonRowe** [comment] 2015-11-29 23:05
@oncelife What setup do you have for removing / cleaning the database? `rspec-rails` doesn't do this by default and it could be something in that is nuking your setup.

**Comment by weimeng** [comment] 2015-11-30 16:27
@oncelife just in case you are using the `database_cleaner` gem on `1.4.0`, you might want to upgrade. there's a known issue where the schema_migrations table is being cleaned as well: https://github.com/DatabaseCleaner/database_cleaner/issues/317

Just ran into this problem myself.

**Comment by samphippen** [comment] 2015-12-01 16:04
I'm going to close this issue because we don't have a reproduction case. @oncelife if you can provide a reproduction case we'll happily re-open this and debug.

**Closed by samphippen** 2015-12-01 16:04 UTC
Labels: Needs reproduction case
