### ISSUE TITLE
view specs doesn't render "current_page?" condition?

### ISSUE THREAD

**Issue by PascalTurbo** [rspec/rspec-rails#1347] opened 2015-04-04 15:56 UTC
Hi There,

I'm trying to test a css class generated while using the current_page? helper:

    RSpec.describe 'my_day/index.html.erb', type: :view do
      it 'should have an active link to my_days' do
        render template: 'my_day/index', layout: 'layouts/application'
        expect(rendered).to have_css('li.active a', text: 'MyDays')
      end
    end

    <li class="<%= 'active' if current_page?(controller: 'my_day', action: 'index') %>"><%= link_to('MyDays', my_day_index_path) %></li>

But this will never match.

So I tried setting the condition true:

    <li class="<%= 'active' if true %>"><%= link_to('MyDays', my_day_index_path) %></li>

And this works. So I think that current_page? isn't evaluated correctly.

**Comment by cupakromer** [comment] 2015-04-04 18:30
:anguished: I can see why this behavior is surprising. TLDR; you will need to [stub this helper](https://www.relishapp.com/rspec/rspec-rails/v/3-2/docs/view-specs/view-spec#passing-view-spec-that-stubs-a-helper-method) in your spec :heart::

```ruby
allow(view).to receive(:current_page?).with(
  controller: 'my_day',
  action: 'index'
).and_return(true)
```

RSpec view specs are intended to allow testing view templates in isolation. When working with a view template in isolation the idea is to treat it as detached from a controller, action, or request path.

However, many applications tend to have a single template used by a single controller and action. RSpec tries to help with this by adding that information via a `controller` object: https://www.relishapp.com/rspec/rspec-rails/v/3-2/docs/view-specs/view-spec-infers-controller-path-and-action

The root of the issue is that `current_page?` doesn't use this information. Checking the [current source](https://github.com/rails/rails/blob/67bb09e28354d203f9c247fef3f4b52af30316ea/actionview/lib/action_view/helpers/url_helper.rb#L539) shows this implementation of the helper only checks the request path.

I think we may be able to adjust things to accommodate this.

**Comment by samphippen** [comment] 2016-04-02 12:36
Closing because of #1402

**Closed by samphippen** 2016-04-02 12:36 UTC
Labels: small
