### ISSUE TITLE
PG::ConnectionBad: PQsocket()

### ISSUE THREAD

**Issue by ivar** [rspec/rspec-rails#1317] opened 2015-02-20 17:15 UTC
Unfortunately, I'm not certain if this an rspec issue or if it relates to interactions with the database connector.

When running a test suite most (95%+) of the time there will an initial failure with:
```
Failure/Error: Unable to find matching line from backtrace
ActiveRecord::StatementInvalid:
PG::ConnectionBad: PQsocket() can't get socket descriptor: BEGIN
```
or
```
Failure/Error: Unable to find matching line from backtrace
ActiveRecord::StatementInvalid:
PG::ConnectionBad: PQsocket() can't get socket descriptor: SAVEPOINT active_record_1
```
that will cause each of the remaining specs to fail with one of the two above error messages.

I am using the [activerecord-postgis-adapter](https://github.com/rgeo/activerecord-postgis-adapter) adapter currently, but the issue existed when using the stock [pg](https://rubygems.org/gems/pg) gem. I thought it might be related to use of the [database_cleaner gem](https://rubygems.org/gems/database_cleaner) but the issue occurs with the same frequency with and without the use of database_cleaner.

I'm not alone with this issue - there are various reports in forums and in projects, but [here is a question on StackOverflow](http://stackoverflow.com/questions/23626372/rspec-pgconnectionbad-pqsocket-cant-get-socket-descriptor) with this exact issue.

**Comment by cupakromer** [comment] 2015-02-21 04:13
This doesn't sound like an rspec issue directly.

If you cannot connect to your database, then specs will fail due to that. However, RSpec leans mostly on raise for all of the database code, so while there's a very slim chance it's RSpec, I'm not currently inclined to think that's the cause.

This sounds like your app has exhausted all of the available database connections. It could be possible if you do a lot of forking in your specs that there are enough spawned processes / threads that will exhaust the database. Though I haven't heard of that in practice it is theoretically possible.

If this is happening on your local system I suggest a reboot / check on the PG side to determine where all of the connections are coming from. I'd also take a look at what your pool size is.

Another thing to consider is if you have a custom 'active_record_helper' or something that you use to test things in isolation. It's possible that is causing the issue.

I have to say, using rspec on many Rails projects, I've never run into this issue.

**Comment by cupakromer** [comment] 2015-02-21 04:15
After reading those SO posts, I'm curious to know what your settings are in your `config/database.yml` file.

**Comment by cupakromer** [comment] 2015-02-21 04:17
You may also find the following links interesting:

- http://omegadelta.net/2014/03/15/the-rails-grim-reaper/
- http://geoff.evason.name/2015/01/18/postgres-ssl-connection-has-been-closed-unexpectedly

**Comment by ivar** [comment] 2015-02-24 23:29
Thanks @cupakromer - I think you're correct about my app has exhausting all of the available database connections. I'm having similar issues with Sidekiq (which is multithreaded) despite having a relatively large db connection pool. 
I've checked our specs for any obvious thread creation and I haven't been able to find anything. Aside from thread creation, is suggestions for things I could be missing?

here is my database.yml:
```
connection_details: &connection_details
  url: <%= ENV['DATABASE_URL'] %>

adapter_defaults: &adapter_defaults
  adapter: postgis
  encoding: utf8
  pool: 25
  timeout: 2000

development:
  <<: *adapter_defaults
  <<: *connection_details

test:
  database: rew_test
  username: rew
  password: rew
  <<: *adapter_defaults

staging:
  <<: *adapter_defaults
  <<: *connection_details

production:
  <<: *adapter_defaults
  <<: *connection_details
```
and a sample `DATABASE_URL` is `postgres://rew:rew@localhost/rew_development`
Note DATABASE URL uses 'postgres' even though we use POSTGIS adapter

**Comment by brandonjmckay** [comment] 2015-03-26 21:00
:+1:

**Comment by brandonjmckay** [comment] 2015-03-26 22:57
I searched our codebase for any references to `reaping`, or `reaping_frequency` as the first article suggests, but I don't see any.

Reverting to `pg: '0.18.0'` seems to fix the issue. Maybe it's a problem in `pg`?

**Comment by brandonjmckay** [comment] 2015-03-26 23:04
I've created an issue with `pg` [here](https://bitbucket.org/ged/ruby-pg/issue/214/pg-connectionbad-pqsocket-when-running).

**Comment by brandonjmckay** [comment] 2015-03-27 19:25
And... I was wrong. It looked like it was working, but it still fails after a few tries. After that it's random.

**Comment by jjg-aframe** [comment] 2015-04-24 13:11
I had something similar, a fork was involved and when the subprocess ended it called some kind `at_exit` function which closed the db connection.  Putting a `Kernel.exit!` at the end of the `fork` block fixed it ...

**Comment by brandonjmckay** [comment] 2015-04-24 19:24
What does a fork look like?

**Comment by brandonjmckay** [comment] 2015-04-24 19:25
Hmmm... will have to look for those calls.

**Comment by jjgreen** [comment] 2015-04-24 19:48
`Process.fork`

**Comment by andela-bolanrewaju** [comment] 2015-04-28 15:34
I saw this [here](https://github.com/gottfrois/dashing-rails/wiki/Possible-problems) 

setting `reaping_frequency: 10` could fix it for you. I haven't tried it though.

**Comment by brandonjmckay** [comment] 2015-04-28 15:52
Thanks!

**Comment by JonRowe** [comment] 2015-04-28 23:36
Closing as this seems not to be an RSpec issue, if you find something we can help with let us know :)

**Closed** 2015-04-28 23:36 UTC

**Comment by mic-2000** [comment] 2015-08-25 07:10
Hi @brandonjmckay 

Can you explain what I should do to fix this issue?

**Comment by brandonjmckay** [comment] 2015-08-30 06:10
No, I'm on a different project currently. Not sure if this got sorted out or not.

**Comment by Arcrammer** [comment] 2015-09-22 15:27
Just ran into the same issue... No hope? 🙁
