### ISSUE TITLE
Test controller actions that require pundit authorize

### ISSUE THREAD

**Issue by p29892p** [rspec/rspec-rails#1695] opened 2016-08-30 05:28 UTC
Hi there,

I tried so many things and end up incompletely. I want to write some specs for my rails app controller that require pundit authorization. I searched for solutions in google and also posted a question in rspec google group, but nothing found. Please some one help me how can i write tests for controller action that require pundit authorization. Here i added my controller action and specs file also.

controller action:
```
def create
    @post = Post.new(post_params)
    authorize @post
    respond_to do |format|
      if @post.save!
        format.html { redirect_to admin_posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
```
and my specs looks like:
```
describe "POST create" do
    let(:user) { FactoryGirl.create(:user, :admin) }
    describe "with valid params" do
      it "creates a new Post" do
        expect {
          post :create, {:post => valid_attributes}, valid_session
        }.to change(Post, :count).by(1)
      end

      it "assigns a newly created post as @post" do
        post :create, {:post => valid_attributes}, valid_session
        expect(assigns(:post)).to be_a(Post)
        expect(assigns(:post)).to be_persisted
      end

      it "redirects to the index page after success" do
        post :create, {:post => valid_attributes}, valid_session
        expect(response).to redirect_to(admin_posts_path)
      end
    end
  end
```
Please help me to resolve this.

**Comment by JonRowe** [comment] 2016-08-30 12:24
Closing as this is not a bug / feature request.

**Comment by JonRowe** [comment] 2016-08-30 12:24
What exactly isn't working?

**Closed by JonRowe** 2016-08-30 12:24 UTC

**Comment by p29892p** [comment] 2016-08-30 15:05
Hi JonRowe.
i'm unable to handle **authorize @post** statement in my controller action. When i removed or commented that statement in my controller action test cases are passing. Can you please figure out what went wrong and how can i resolve this?

**Comment by JonRowe** [comment] 2016-08-30 23:46
You need to add an authorization step into your test then, I'm not familiar with pundit but I'll guess it's session based so you need to do a login step first, then follow up with your post calls.

**Comment by p29892p** [comment] 2016-08-31 06:15
Thank you JonRowe. I'm very beginner with Rspec. I got stuck with authorization step and if you got any solution please post it here. Then i'll be know how to do that and that really helps me.
