### ISSUE TITLE
provide json data for GET action

### ISSUE THREAD

**Issue by BranLiang** [rspec/rspec-rails#1922] opened 2017-12-01 03:10 UTC
Scenario:
* Test GET action with provide json data as params

Problem:
* Can not access json data inside controller when testing with type => controller, Using client like Insomnia for real api call works fine.

Guessing:
* Missing content-type header on request.

Tried:
* request.headers['Content-Type'] = 'application/json'

QUESTION:
How can I correctly set content-type to application/json in rspec or can I just make the default controller content-type to be 'application/json'

**Comment by JonRowe** [comment] 2017-12-01 11:27
In general Github issues is not the best place to ask for help with writing specs, but if you paste a gist containing the snippet someone might be able to help. This could also be a duplicate of #1655 if it is just the headers you are having trouble with.

**Closed by JonRowe** 2017-12-01 11:27 UTC
