### ISSUE TITLE
Error: uninitialized constant Rspec::Generators::Base::RSpec.

### ISSUE THREAD

**Issue by danielmyasnikov** [rspec/rspec-rails#1301] opened 2015-02-06 01:02 UTC
[WARNING] Could not load generator "generators/rspec/model/model_generator". Error: uninitialized constant Rspec::Generators::Base::RSpec.
/opt/rubies/2.1.3/lib/ruby/gems/2.1.0/gems/rspec-rails-3.2.0/lib/generators/rspec.rb:10:in `<class:Base>'
/opt/rubies/2.1.3/lib/ruby/gems/2.1.0/gems/rspec-rails-3.2.0/lib/generators/rspec.rb:9:in `<module:Generators>'
/opt/rubies/2.1.3/lib/ruby/gems/2.1.0/gems/rspec-rails-3.2.0/lib/generators/rspec.rb:7:in `<module:Rspec>'
/opt/rubies/2.1.3/lib/ruby/gems/2.1.0/gems/rspec-rails-3.2.0/lib/generators/rspec.rb:5:in `<top (required)>'
/opt/rubies/2.1.3/lib/ruby/gems/2.1.0/gems/rspec-rails-3.2.0/lib/generators/rspec/model/model_generator.rb:1:in `<top (required)>'
/opt/rubies/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/generators.rb:281:in `block (2 levels) in lookup'
/opt/rubies/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/generators.rb:277:in `each'
/opt/rubies/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/generators.rb:277:in `block in lookup'
/opt/rubies/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/generators.rb:276:in `each'
/opt/rubies/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/generators.rb:276:in `lookup'
/opt/rubies/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/generators.rb:138:in `find_by_namespace'
/opt/rubies/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/generators.rb:155:in `invoke'
/opt/rubies/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/generate.rb:11:in `<top (required)>'
/opt/rubies/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:135:in `generate_or_destroy'
/opt/rubies/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:51:in `generate'
/opt/rubies/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
/opt/rubies/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
./bin/rails:4:in `require'
./bin/rails:4:in `<main>'
Could not find generator rspec:model.

**Comment by danielmyasnikov** [comment] 2015-02-06 01:03
Fixed locally the issue by adding:

    require 'rspec/rails/feature_check'

to `lib/generators/rspec.rb:2`

    rspec-rails v.3.2.0

**Comment by cupakromer** [comment] 2015-02-06 02:36
@danielmyasnikov what command did you run to cause the error? I was not able to reproduce this.

**Comment by JonRowe** [comment] 2015-02-06 03:41
This looks like an autoloading issue...

**Comment by danielmyasnikov** [comment] 2015-02-06 04:02
rails generate rspec:model widget

On 6 February 2015 at 14:41, Jon Rowe <notifications@github.com> wrote:

> This looks like an autoloading issue...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rspec/rspec-rails/issues/1301#issuecomment-73178387>.
>



-- 
*Kind regards*
*Daniel Myasnikov*
*#{ruby_on_rails}_dev*

**Comment by bodrovis** [comment] 2015-02-06 14:45
I am having the same issue when running `rails g model test` (or controller) in the engine.

**Comment by arashm** [comment] 2015-02-08 18:53
I'm having the same issue after updating to RSpec 3.2.0

**Comment by joowh85** [comment] 2015-02-09 11:28
+1
Same issues in the rails mountable plugin application.

**Comment by cupakromer** [comment] 2015-02-10 04:39
I'll add the fix but I'd like to understand the root cause. I'd appreciate if people could let me know:

- What OS they have the problem on
- Are you using a binstub, `bundle exec`, or other means of running the generator
- If using a binstub are you using spring or another pre-loader?

**Comment by arashm** [comment] 2015-02-10 07:20
* I have a linux (ArchLinux)
* I have binstubs and used it to generate a model
* I'm using spring

**Comment by danielricecodes** [comment] 2015-02-10 07:29
+1

@danielmyasnikov, your workaround worked for me.

Environment:
* OSX 10.9.5
* Not using Binstubs or Spring
* Using RVM and Bundler

Command:
`rails g model Thing name:string -p`

Using:
* Bundler 1.7.13
* Rspec-Rails 3.2.0
* Rails 4.2.0

`application.rb` snippet:
```ruby
  config.generators do |g|
      g.template_engine :slim
      g.test_framework :rspec, :view_specs => false, :routing_specs => false
      g.fixture_replacement :factory_girl, :dir => 'spec/factories'
      g.assets = false
      g.helper = false
  end
```

**Comment by bodrovis** [comment] 2015-02-10 11:21
I am using Windows 7 x64, running via `rails g model ...`.

**Comment by cupakromer** [comment] 2015-02-10 16:33
@arashm can you paste the contents of your `bin/rails` file?

@danielricecodes you're setup is similar to mine but I'm using binstubs and chruby

Thank you :heart: to everyone for providing more information. This is a very odd case of Rails autoloading being so strange across environments, even those that appear to be similar.

**Comment by cupakromer** [comment] 2015-02-10 16:43
For those of you using spring, can you try running `bin/spring stop` (or your equivalent) then attempting to run the generator again.

I've pushed the fix up in a PR. I'll merge it soon, but we likely won't push out a new minor until Sunday / Monday. Let me know if this is causing a lot more pain for you all.

**Closed** 2015-02-10 22:28 UTC

**Comment by emclab** [comment] 2015-02-12 19:07
I have the same issue with rspec 3.2.0/ rails 4.2.0 on rails engine. Running win8

**Comment by JonRowe** [comment] 2015-02-12 23:01
It'll be fixed in the next release. (rspec-rails 3.2.1)
