### ISSUE TITLE
Rails 5 / Rspec 3.5.0 -- setting request headers?

### ISSUE THREAD

**Issue by ledbettj** [rspec/rspec-rails#1655] opened 2016-07-05 14:20 UTC
Hi,

I had a spec working under Rails 4 / Rspec 3.4.4 that looked like this:

``` ruby
it 'does something with the referrer' do
  allow(request).to receive(:referrer).and_return('aol.com')
  expect(Foo).to receive(:bar).with('aol.com')
  get :endpoint
end
```

After upgrading, it looks like `request.referrer` is not stubbed correctly and `request.referrer` in the controller returns `nil`.

I tried rewriting like so:

``` ruby
get :endpoint, { params: {} }, headers: { 'HTTP_REFERER' => 'aol.com' }
```

But I wasn't able to get that header, or actually any header passed through to the controller.

Any suggestions?

**Comment by ledbettj** [comment] 2016-07-05 14:38
Setting the header in `request.env` works -- is that the recommended way to accomplish this?

**Comment by JonRowe** [comment] 2016-07-05 23:12
Try: `get :endpoint, params:  {}, headers: { 'HTTP_REFERER' => 'aol.com' }`
`

**Comment by samphippen** [comment] 2016-07-22 10:47
@ledbettj 
Thanks for the issue. We need a little more detail to be able to reproduce this.

Could you please provide us with a rails app that we can clone that demonstrates the issue. Specifically it'd be great if

1)  you could `rails new` an application and commit
2) make all the changes necessary to reproduce the issue and commit

then, provide us with a description of how to clone your application and reproduce the issue.

Thanks :)

**Comment by ledbettj** [comment] 2016-07-25 13:59
I've pushed a basic example [here](https://github.com/ledbettj/rspec-repro).

`ApplicationController#index` simply renders the HTTP referrer as JSON.  The specs for this action try to set the referrer in several ways; only the last -- setting `request.env` -- works.

```shell
git clone https://github.com/ledbettj/rspec-repro.git repro
cd repro
bundle
bundle exec rake spec
```

Output:

```
Failures:

  1) ApplicationController when stubbing referrer sets the referrer correctly
     Failure/Error: expect(body['from']).to eq(aol)

       expected: "aol.com"
            got: nil

       (compared using ==)
     # ./spec/controllers/application_controller_spec.rb:11:in `block (3 levels) in <top (required)>'

  2) ApplicationController when passing referrer as a hash sets the referrer correctly
     Failure/Error: expect(body['from']).to eq(aol)

       expected: "aol.com"
            got: nil

       (compared using ==)
     # ./spec/controllers/application_controller_spec.rb:18:in `block (3 levels) in <top (required)>'

  3) ApplicationController when passing in two hashes sets the referrer correctly
     Failure/Error: expect(body['from']).to eq(aol)

       expected: "aol.com"
            got: nil

       (compared using ==)
     # ./spec/controllers/application_controller_spec.rb:25:in `block (3 levels) in <top (required)>'

Finished in 0.04602 seconds (files took 2.82 seconds to load)
4 examples, 3 failures
```

Let me know if anything else would help.

**Comment by richddr** [comment] 2016-07-28 02:14
request.env did not work for me. Any update on this?

**Comment by samphippen** [comment] 2016-07-28 11:14
@richddr looks like nobody from the RSpec core team has had a chance to look at this yet. If you really need a fix to this, you're more than welcome to use the reproduction case above as a starting point for debugging and see if you can fix the problem :)

**Comment by richddr** [comment] 2016-07-28 17:52
Update: For my API only app I managed to get around it using by `controller.request.headers` instead of `request.env`

```ruby
controller.request.headers['X-Secret-Header'] = my_secret_header
```

**Comment by sebastian-julius** [comment] 2016-09-29 09:38
I worked around this like so. Maybe it helps you, too. Not the prettiest solution but effective.

```ruby
  let(:headers) { some: "header" }
  # ...
  request.headers.merge! headers
  post :endpoint, params: params
```

**Comment by Stankec** [comment] 2016-10-04 21:16
I tried to fix this issue but don't see anything wrong with the way it currently is. (I don't know if this is a regression)

Just to explain as to why this is happening.

Regarding the stubbed method. If you take a look at __ActionController::TestCase::Behaviour__ you will notice that all HTTP methods (`get`, `post`, `delete`, ...) get funneled into the `process` method. The `process` method builds a new `TestRequest` object with the `request.env` object from your test. That's why stubbed methods won't work.

Regarding the remaining two options - passing the headers as params. This also won't work. If you take a look at the above-mentioned class you can notice that only the `session`, `flash`, `method`, `body`, `xhr` params get processed and all others are ignored.

This leaves you with the option to edit `request.env` direcly or through `request.headers` as @sebastian-julius outlined.

**Comment by richddr** [comment] 2016-10-04 21:53
Sorry, forgot to post an update here. I also ended up working around it the same as @sebastian-julius did.

**Comment by douglaslise** [comment] 2016-10-23 03:27
You cannot stub `request` because it is recreated in [this](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/test_case.rb#L471) line of `actionpack/lib/action_controller/test_case.rb`:
```ruby
  @request = TestRequest.new scrub_env!(@request.env), @request.session, @controller.class
```
So, the `request` seen in the controller action is another instance of the `request` accessible/modified in the spec, and neither all the `env` part are kept.

**Comment by dcrockwell** [comment] 2016-12-08 07:48
This cost me a lot of time tonight. Thanks to @sebastian-julius for the workaround.

I expected this to work:

``` ruby
get :create, headers: { Key: "SomeKey" }
```

Ended up doing this, per @sebastian-julius's workaround:

``` ruby
headers = { :Key => @api_key.token }
request.headers.merge! headers
get :create
```

**Comment by dpsk** [comment] 2017-01-09 10:57
For me the issue is that `req.headers['CustomHeader']` is `nil` while `req.env['CustomHeader']` contains required value. For production environment it's the other way around with Rails 5.0 and rspec 3.5.0.
Am i missing something?

**Comment by pawandubey** [comment] 2017-01-13 08:25
I faced this issue today and I dug a little. It seems that for request specs, rspec-rails correctly leads us to `ActionDispatch::IntegrationTest::Behavior` as seen here: https://github.com/rspec/rspec-rails/blob/ace2f2b922a7e5f79bfa8f667a87b1ef5342425e/lib/rspec/rails/example/request_example_group.rb#L15

But for controller tests, it leads us to the old and now deprecated `ActionController::TestCase::Behavior`, as seen here: https://github.com/rspec/rspec-rails/blob/ace2f2b922a7e5f79bfa8f667a87b1ef5342425e/lib/rspec/rails/example/controller_example_group.rb#L13

`ActionDispatch::IntegrationTest` has support for extracting the `header` key and setting headers normally works, but breaks in `ActionController::TestCase` and hence it works in request specs, but not in controller specs.

I think this is a bug and the core team should take a look at it.

**Comment by tvdeyen** [comment] 2017-07-13 16:56
Nothing of the above mentioned fixes worked for me. Ended up with:

```ruby
before do
  allow_any_instance_of(ActionController::TestRequest).to receive(:referer) do
    '/imprint'
  end
end
```

**Comment by jfragoulis** [comment] 2017-09-26 13:38
As for @JonRowe 's example, you cannot set the headers explicitly in the request as we can in the method's signature in [5.0](https://github.com/rails/rails/blob/5-0-stable/actionpack/lib/action_controller/test_case.rb) and [5.1](https://github.com/rails/rails/blob/5-1-stable/actionpack/lib/action_controller/test_case.rb).

**Comment by JonRowe** [comment] 2017-09-26 22:42
@jfragoulis This method delegates to Rails, it supports the same parameter format as your version of Rails.

**Comment by mikegee** [comment] 2017-10-03 11:55
Here's a bit of context regarding why this issue isn't getting much attention: [request specs are preferred over controller specs](https://github.com/rspec/rspec-rails/pull/1839)

This recommendation like the one near the top will work in a request spec:

```ruby
get '/endpoint', params: {}, headers: { 'HTTP_REFERER' => 'aol.com' }
```

**Comment by jfragoulis** [comment] 2017-10-24 07:42
Everyone seems to have found the way to do it. In [request specs](https://github.com/rspec/rspec-rails/issues/1655#issuecomment-333819477) you can pass the headers as an argument, in [controller specs](https://github.com/rspec/rspec-rails/issues/1655#issuecomment-338798517) you need to set the headers directly on the request object.

Should this be marked as closed then?

**Comment by KevinColemanInc** [comment] 2017-10-25 20:15
Does the request object get reset between requests?

It seems odd if you want to do two concurrent requests, one with a header and one without.  In between them you have modify the request params.

```ruby
get :show, id: 1, headers: { 'Authenticated token' }
response.code.should be 200

get :show, id:1
response.code.should be 401
```

**Comment by jfragoulis** [comment] 2017-10-26 10:33
@KevinColemanInc between requests no, and why should they? It resets for each test, and each test should have one request.

**Comment by falegk** [comment] 2017-12-29 14:39
The only thing that worked for me. (**rails: 5.1.4 & rspec-rails 3.7.2**)

```
before(:all) do
    header 'Authorization', "Bearer <token>"
    get '/my/endpoint'
end
```

**Comment by obie** [comment] 2018-03-09 19:43
I ended up here trying to figure out how to mock the `request.domain` ... since doubles are not allowed in global RSpec context, I just brute forced it by overriding the method on `TestRequest` like this:

```
ActionController::TestRequest.class_eval do
  def domain
    "example.com"
  end
end
```

**Comment by mikegee** [comment] 2018-03-21 14:33
@andreymakovenko yup, it works in request specs.

**Comment by ArielAleksandrus** [comment] 2018-05-24 01:39
why so many downvotes on @andreymakovenko reply?

**Comment by mikegee** [comment] 2018-05-24 02:00
@ArielAleksandrus this issue is about controller specs not request specs.

**Comment by crusadergo** [comment] 2018-06-09 05:35
for example:
      request.headers.merge!(valid_headers)
      post :create, params: { order: order.attributes }

**Comment by JonRowe** [comment] 2018-10-11 08:51
Dependant on what your `type: :api` triggers here, will depend on how you send headers

**Comment by Sirpez** [comment] 2018-10-11 22:08
Sorry, my bad, I'm using controller type now, but the main issue was something else, unrelated do Rspec. Everything works now! Thanks!

**Comment by OrestF** [comment] 2018-11-16 12:20
Rails 5.2 this works for me
`post path, params: params.to_s.to_json, headers: headers`

**Comment by lukad** [comment] 2018-11-20 10:12
Before you post your solution please make sure that you understand the difference between request specs and controller specs. This issue is about controller specs.
Reading all the replies here is really frustrating.

**Comment by zerokol** [comment] 2018-12-18 15:00
@fnmendez works well, I recommend to check in controller if simple "puts" is the values are right placed; I spend 5 hours thinking that the solution not works, but, I was not the right values in models (fixtures)

**Comment by dennym** [comment] 2019-03-11 13:38
`get '/foobar.json', {}, { 'HTTP_SESSION_ID' => 'XXXX', .... }`

Using this works for controller/feature specs. The only thing you have to make sure is that the headers are on the second position of the args. That's why the empty hash.  
Since they get utilized here https://github.com/rails/rails/blob/e2fcb2b4aec69e10a01cebfe51bbd280ce6d5a93/actionpack/lib/action_controller/test_case.rb#L602

As @pawandubey its the different module request and controller specs are using.

Unfortunatly when you use the snippet like top one rubocop will complain because 
 of `Rails/HttpPositionalArguments: Use keyword arguments instead of positional arguments for http call`
This also a topic over at rubocop-hq/rubocop#5888. But it seems stall.

**Comment by kiecoorp** [comment] 2019-05-16 07:57
For HTTP_REFERER use symbol and not string !

`post "/api/v1/kpulse", params: params, headers: { HTTP_REFERER: 'kpulse.fr'  }`

**Comment by salmagomaa** [comment] 2019-07-11 11:13
This solution worked for me too 
https://robert-reiz.com/2013/08/09/http_referer-for-rspec-is-missing/

**Comment by Xanthus** [comment] 2019-09-09 12:29
Using Rails 5.2 and RSpec 3.8 and I'm struggling with this too. No matter what I try, the request submitted to the controller doesn't have the headers I set. I'm testing my base API controller's inherited token verification. It has a before_action that reads the token from the header and verifies it before continuing. The before_action triggers but the headers available are blank (save for the default security headers configured in Rails). My app is not a Rails API app but it has API-only controllers.

The base API controller looks something like this:

````
module Api
  module V1
    class ApiController < ActionController::API

      before_action :read_token_from_header

      pirvate

      def read_token_from_header
        if response.headers['Authorization'].present?
          # Read the token and if it's not valid -> return head :unauthorized
        end

        true
      end
    end
  end
end
````

The spec is shown below.

````
require 'rails_helper'

RSpec.describe Api::V1::ApiController, type: :controller do
  controller(Api::V1::ApiController) do
    def index
      head :ok
    end
  end

  let(:token_signed_with_fake_key) { ... }

  describe 'token signature verification for any action' do
    context 'for a token that was signed with an invalid secret key' do
      it 'returns 401 Unauthorized' do
        request.set_header('Authorization', "Bearer #{token_signed_with_fake_key}")
        get :index
        expect(response.code).to eq '401'
      end
    end
  end
end
````

I'm at a complete loss. @MiguelCorti my situation sounds exactly like yours. Do you remember how you solved this?

**Comment by fabioaraujo121** [comment] 2019-09-26 13:08
For **Rails 5.2.3** and **Rspec 3.8**
Just used the `request.headers.merge!(valid_headers)`
```ruby
let(:valid_attributes) {
    {to_wallet: "wallet", value: 100.00}
}

let(:valid_headers) { { HTTP_USERTOKEN: "Token12345678"} }

it "creates a new Transaction" do
        request.headers.merge!(valid_headers) # This line right here!!!
        expect {
          post :create, params: {transaction: valid_attributes}
        }.to change(Transaction, :count).by(1)
end
```

**Comment by Schwad** [comment] 2019-11-05 12:30
Hello from 2019! 

Just want to confirm I came here trying to set headers on a controller test and that @sebastian-julius ' approach (though I slightly modified it) worked great for me! Thank you! :)

**Comment by yogo-chen** [comment] 2019-11-12 08:25
This works for me on **rspec 3.8.0**
```
it 'return 200' do
  auth = 'Basic ' + Base64.strict_encode64('username:password')
  params = { foo: 'bar' }
  
  header('Authorization', auth)
  
  get '/baz', params

  expect(last_response.status).to eq 200
end
```

**Comment by mrothenbuhler** [comment] 2019-11-26 01:31
> For me the issue is that `req.headers['CustomHeader']` is `nil` while `req.env['CustomHeader']` contains required value. For production environment it's the other way around with Rails 5.0 and rspec 3.5.0.
> Am i missing something?

Same! It was `request.headers['myHeader']` was missing. Man that took me hours.

**Comment by pirj** [comment] 2019-11-26 20:36
Are there any volunteers to update [the doc](https://github.com/rspec/rspec-rails/blob/master/features/controller_specs/README.md#examples) and add feature test similar to [the cookie one](https://github.com/rspec/rspec-rails/blob/master/features/controller_specs/cookies.feature)?

**Closed** 2020-01-11 13:27 UTC
Labels: Has reproduction case

**Comment by 7wapnil** [comment] 2021-08-11 10:00
> This works for me on **rspec 3.8.0**
> 
> ```ruby
> it 'return 200' do
>   auth = 'Basic ' + Base64.strict_encode64('username:password')
>   params = { foo: 'bar' }
>   
>   header('Authorization', auth)
>   
>   get '/baz', params
> 
>   expect(last_response.status).to eq 200
> end
> ```

Did'nt work

**Comment by imnithin** [comment] 2023-02-01 10:13
This might work - on rspec-rails 3.8 works

`request.env['HTTP_REFERER'] = 'aol.com'`
