### ISSUE TITLE
Template variants on 4.0.0.beta2 with Rails 6.0.0.rc1

### ISSUE THREAD

**Issue by jaredmoody** [rspec/rspec-rails#2114] opened 2019-04-30 00:18 UTC
The following spec passes on rspec-rails 3.8.2, rails 5.2.3, but errors on rspec-rails 4.0.0.beta2, rails 6.0.0.rc1:

```ruby
# spec/views/layouts/sidebars/_main.html+app.haml_spec.rb
require 'rails_helper'

RSpec.describe 'layouts/sidebars/_main.html+app.haml', type: :view do
  it 'renders' do
    render
  end
end
```

```
Failures:

  1) layouts/sidebars/_main.html+app.haml renders
     Failure/Error: render

     ArgumentError:
       Invalid formats: :"html+app"
     # /Users/jaredmoody/.gem/ruby/2.5.5/gems/haml-5.0.4/lib/haml/helpers/action_view_mods.rb:14:in `render'
     # ./spec/views/layouts/sidebars/_main.html+app.haml_spec.rb:5:in `block (2 levels) in <top (required)>'
```

I was also able to duplicate this with an `html+app.erb` template so I don't think it's haml or haml-rails either.

**Comment by benoittgt** [comment] 2019-04-30 09:19
Hello

Do you think you can provide a reproduction case? I have started an app here https://github.com/benoittgt/testing_6_0_0_rc1 and invited you as a collaborator. 

Thanks

**Comment by JonRowe** [comment] 2019-04-30 09:34
Can I ask if this works with Rails 5.2.3 and RSpec 6.0.0.rc1? Might this be a change at the Rails ends?

**Comment by jaredmoody** [comment] 2019-04-30 17:55
> Do you think you can provide a reproduction case? I have started an app here https://github.com/benoittgt/testing_6_0_0_rc1 and invited you as a collaborator.

Yes, I will add code there to reproduce.

> Can I ask if this works with Rails 5.2.3 and RSpec 6.0.0.rc1? Might this be a change at the Rails end? 

I think you have wrong gem versions here? Do you mean Rails 6.0.0.rc1 and some different version of rspec-rails?

**Comment by samphippen** [comment] 2019-04-30 18:41
@jhawthorn

**Comment by jhawthorn** [comment] 2019-04-30 20:11
This is due to a change in Rails, specifically https://github.com/rails/rails/pull/35661, but IMO the new behaviour is good. The issue is [this filename parsing in rspec-rails](https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/example/view_example_group.rb#L130-L145) doesn't actually support variants (and so it passes a format like `html+app`). I think it might also have weird behaviour if a format or handler isn't specified (ie. `something.en.erb` would be `format: :en, handler: :erb`).

I'm hoping to break this even more in future versions of Rails so I'm glad we're catching it now 🙂.

**Comment by benoittgt** [comment] 2019-04-30 20:17
Thanks a lot @jhawthorn

**Comment by samphippen** [comment] 2019-05-01 19:33
This is fixed in 4-0-dev

**Closed by samphippen** 2019-05-01 19:33 UTC
Labels: Needs reproduction case
