### ISSUE TITLE
Rspec drops my database because of Postgres Sequence

### ISSUE THREAD

**Issue by brentgreeff** [rspec/rspec-rails#2600] opened 2022-05-20 08:07 UTC
## What Ruby, Rails and RSpec versions are you using?

Ruby version: `ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-darwin21]`

Rails version:`Rails 7.0.3`

RSpec version:
```RSpec 3.11
  - rspec-core 3.11.0
  - rspec-expectations 3.11.0
  - rspec-mocks 3.11.1
  - rspec-rails 5.1.2
  - rspec-support 3.11.0
  ```

## Observed behaviour

Postgres sequence in migration causes rspec to drop my test database. 

Here is sequence in migration:
```ruby 
def up
    execute <<-SQL
      CREATE SEQUENCE number_seq START 1;
      ALTER SEQUENCE number_seq OWNED BY accounts.number;
      ALTER TABLE accounts ALTER COLUMN number SET DEFAULT nextval('number_seq');
    SQL
  end
```
If I remove this migration then rspec works perfectly.

With this migration I get:

```
Running: spec/system/view_homepage_spec.rb
Migrations are pending. To resolve this issue, run:

        bin/rails db:migrate RAILS_ENV=test

You have 1 pending migration:

20220519231509_add_number_sequence.rb

While loading rails_helper an `exit` / `raise SystemExit` occurred, RSpec will now quit.
Failure/Error: exit 1

SystemExit:
  exit
# ./spec/rails_helper.rb:17:in `exit'
# ./spec/rails_helper.rb:17:in `rescue in <top (required)>'
# ./spec/rails_helper.rb:13:in `<top (required)>'
# ------------------
# --- Caused by: ---
# ActiveRecord::PendingMigrationError:
#   
#   
#   Migrations are pending. To resolve this issue, run:
#   
#           bin/rails db:migrate RAILS_ENV=test
#   
#   You have 1 pending migration:
#   
#   20220519231509_add_number_sequence.rb
```

If I run `bin/rails db:migrate RAILS_ENV=test` - and then run rspec again - `it drops my schema completely.

I am not sure what rspec is doing - but my test DB is there, but the schema is gone.

If I delete this migration - drop my database - and then re-run migrations then Rspec behaves normally - it does not blitz my schema on every test run.

I want to continue using `schema.rb` - this issue might be related - https://stackoverflow.com/questions/64950027/migration-not-executed-from-rspec

I also have
```ruby
begin
  ActiveRecord::Migration.maintain_test_schema!
rescue ActiveRecord::PendingMigrationError => e
  puts e.to_s.strip
  exit 1
end
```

## Expected behaviour

- I would expect my test database schema not to disappear just because I have a sequence.

## Can you provide an example app?

I could, but its probably going to be a lot faster to find an alternative solution - ie remove the postgres sequence.

**Comment by pirj** [comment] 2022-05-20 08:20
> If I run bin/rails db:migrate RAILS_ENV=test - and then run rspec again - `it drops my schema completely.

I don't quite understand. When it does so, and what does that?
Would running `rails console -e test` work properly after `rails db:migrate RAILS_ENV=test`?
Or is it only broken after running `rspec`?
Mind showing your `spec/rails_helper.rb`/`spec/spec_helper.rb`?

Is there anything in `logs/test.log`?

Normally, you don't have to run migrations in the `test` env, you usually `rails db:schema:load RAILS_ENV=test`, and the test DB schema is initialized from `db/schema.rb`.
If subsequently, Rails complains that migrations are pending, your `db/schema.rb` must be out of date.

Normally, `rspec-rails` has nothing to do with the DB initialization, and there's apparently some misconfiguration.

**Comment by brentgreeff** [comment] 2022-05-20 08:57
Its definitely not mis-configured when I remove the Postgres Sequence from the migrations.

`rails console -e test` - works perfectly.
ie the database is not dropped.

If I run `bundle exec rspec` **nothing else**.
I get this output: 

```sql
ActiveRecord::InternalMetadata Pluck (1.5ms)  SELECT "ar_internal_metadata"."value" FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "schema_sha1"], ["LIMIT", 1]]
  ActiveRecord::SchemaMigration Pluck (2.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
  ActiveRecord::InternalMetadata Pluck (1.5ms)  SELECT "ar_internal_metadata"."value" FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]]
  ActiveRecord::SchemaMigration Pluck (1.6ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
  ActiveRecord::InternalMetadata Pluck (2.1ms)  SELECT "ar_internal_metadata"."value" FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]]
  ActiveRecord::SchemaMigration Pluck (1.7ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
  ActiveRecord::InternalMetadata Pluck (1.7ms)  SELECT "ar_internal_metadata"."value" FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]]
   (30.4ms)  DROP DATABASE IF EXISTS "axs_test"
   (174.1ms)  CREATE DATABASE "axs_test" ENCODING = 'unicode'
  SQL (8.3ms)  CREATE EXTENSION IF NOT EXISTS "pgcrypto"
  SQL (1.8ms)  CREATE EXTENSION IF NOT EXISTS "plpgsql"
   (1.8ms)  DROP TABLE IF EXISTS "accounts" CASCADE
   (4.3ms)  CREATE TABLE "accounts" ("id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY, "name" character varying, "vat" character varying, "address" character varying, "created_at" timestamp(6) NOT NULL, "updated_at" timestamp(6) NOT NULL, "number" bigint DEFAULT nextval('number_seq'::regclass) NOT NULL)
   (9.8ms)  CREATE TABLE "schema_migrations" ("version" character varying NOT NULL PRIMARY KEY)
   (7.4ms)  CREATE TABLE "ar_internal_metadata" ("key" character varying NOT NULL PRIMARY KEY, "value" character varying, "created_at" timestamp(6) NOT NULL, "updated_at" timestamp(6) NOT NULL)
  ActiveRecord::SchemaMigration Pluck (2.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
```

As you can see - the DB is being dropped and it looks like the structure is recreated. - maybe using `schema::load`

The test tells me that ALL my migrations are pending. - and if I connect to the DB with another client - I can see that there are **no tables** - except for `schema_migrations` and `ar_internal_metadata`
and yes - `schema.rb` has tables.

`Normally, you don't have to run migrations in the test env, you usually rails db:schema:load RAILS_ENV=test, and the test DB schema is initialized from db/schema.rb.
If subsequently, Rails complains that migrations are pending, your db/schema.rb must be out of date.`

Yes - i am sure that its out of data because I am using a Postgres Sequence - and Sequences are not compatible with `schema.rb` - I have isolated this into its own migration - so that i can still use `schema:load` - and run this afterwards.

In all my experience - if I add a migration to an existing db - and then run tests - rspec will run this pending migration - it doesnt run `schema:load` - I can see in the test log that it normally runs just the pending migration - not nuke my whole DB,

spec/spec_helper.rb
```ruby
RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.shared_context_metadata_behavior = :apply_to_host_groups

  config.filter_run_when_matching :focus

  config.example_status_persistence_file_path = "spec/examples.txt"

  config.disable_monkey_patching!

  if config.files_to_run.one?
    config.default_formatter = "doc"
  end

  # config.profile_examples = 10

  config.order = :random

  Kernel.srand config.seed
end
```

spec/rails_helper.rb
```ruby
require 'spec_helper'
ENV['RAILS_ENV'] ||= 'test'
require_relative '../config/environment'

abort("The Rails environment is running in production mode!") if Rails.env.production?
require 'rspec/rails'
# Add additional requires below this line. Rails is not loaded until this point!

Dir[
  Rails.root.join("spec", "support", "**", "*.rb")
].sort.each { |f| require f }

begin
  ActiveRecord::Migration.maintain_test_schema!
rescue ActiveRecord::PendingMigrationError => e
  puts e.to_s.strip
  exit 1
end

RSpec.configure do |config|
  config.fixture_path = "#{::Rails.root}/spec/fixtures"

  config.include Helpers, type: :system

  config.use_transactional_fixtures = true

  config.infer_spec_type_from_file_location!

  config.filter_rails_from_backtrace!
  # config.filter_gems_from_backtrace("gem name")
end
```
As you can see - very standard - the issue is around the Postgres Sequence - it seems that RSpec thinks that this is `data` - and needs to clean the db.

**Comment by pirj** [comment] 2022-05-20 09:14
> RSpec thinks that this is data - and needs to clean the db.

RSpec does not have anything to do with cleaning the DB.

I'd suggest using [this gem](https://github.com/basecamp/marginalia) to pinpoint the code that runs `DROP DATABASE IF EXISTS "axs_test"`. After that, can you please set a breakpoint with `binding.irb` in that code and checking `caller_locations`. That would allow us to better understand what's going on.

**Comment by brentgreeff** [comment] 2022-05-20 11:52
I am using Rails7 and I already see the location of SQL queries in the dev log - not sure why its not in the test log also. - I will need to come back to this later - I will probably drop the postsequence because I know it works without it. - confirm absolutely that this is the case - and then try https://github.com/basecamp/marginalia - thanks for the support. - if rspec is not dropping the db then something in rails that rspec depends on is obv doing it - thanks again.

**Comment by pirj** [comment] 2022-05-20 12:27
The quickest way to find out is to set a breakpoint in https://github.com/rails/rails/blob/3872bc0e54d32e8bf3a6299b0bfe173d94b072fc/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L54. Can you please do this and post the backtrace?

**Comment by brentgreeff** [comment] 2022-05-20 17:22
I will have to come back to this - I removed the Postgres-Sequence and everything works perfectly. -

**Comment by pirj** [comment] 2022-05-20 18:18
Ok. I'll close this for now. Please don't hesitate to reopen if you happen to reproduce and find that RSpec Rails is the culprit.

**Closed by pirj** 2022-05-20 18:18 UTC

**Comment by allisonphillips** [comment] 2024-07-25 08:20
You can run into the pending migration issue if you're trying to recreate or rebuild the DB while something else is still accessing it. I was using a GUI tool to look at my test DB while debugging why a secondary non-public Postgres schema was being deleted from my test DB every time I ran Rspec... I ran into this when I tried to run a drop/create/migrate on my test DB or after running tests whenever I triggered the action before disconnecting from it in the GUI tool.

The output for a Postgres schema created in a migration via the `create_schema` method isn't actually reflected anywhere in the schema dump, so my suspicion around the cause of my problem (haven't had a chance to validate it yet) is that that actual resetting of the DB between examples is loading from the post-migration schema dump. It seems possible that the raw SQL you're executing in your migration may similarly not be reflected accurately in a schema dump and/or the way that migration is trying to force autoincremented sequencing reads like it could easily result in some odd locking scenarios when running in a test environment with transactions.
