### ISSUE TITLE
before_filter/after_filter deprecation warning

### ISSUE THREAD

**Issue by connorshea** [rspec/rspec-rails#1561] opened 2016-02-25 20:27 UTC
I tested to make sure this still occurs on the master branch, here are the deprecation warnings I'm seeing:

```
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from <module:HelperExampleGroup> at /Users/connor/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-rails-41628f82e70a/lib/rspec/rails/example/helper_example_group.rb:10)
DEPRECATION WARNING: after_filter is deprecated and will be removed in Rails 5.1. Use after_action instead. (called from <module:HelperExampleGroup> at /Users/connor/.rvm/gems/ruby-2.3.0/bundler/gems/rspec-rails-41628f82e70a/lib/rspec/rails/example/helper_example_group.rb:10)
```

`rails 5.0.0.beta3`, `rspec-rails` & co. on their respective master branches.

`*_filter` should be replaced by `*_action`, I believe.

**Comment by JonRowe** [comment] 2016-02-25 23:30
The line referenced is the inclusion of `ActionView::TestCase::Behaviour` so this might be a no op for us at the moment (e.g. it's coming from rails directly and we need to wait for them to fix it).

**Comment by connorshea** [comment] 2016-03-06 21:18
@JonRowe can you open an issue in Rails, or should I? I'm not entirely sure I understand where that file would be.

**Comment by JonRowe** [comment] 2016-03-09 01:59
See if you can replicate this out side of RSpec by including that module into an empty class, if you can you can use that to demonstrate the issue to Rails

**Comment by gregblass** [comment] 2016-03-14 19:21
Just confirming that I'm also seeing this. Every time I run tests I get that depreciation warning.

**Comment by JonRowe** [comment] 2016-03-14 23:26
Can you see if you can replicate this outside of RSpec by including `ActionView::TestCase::Behaviour` into an empty class somewhere? We don't use those methods so they're coming from Rails internally somewhere.

**Comment by gregblass** [comment] 2016-03-15 02:52
Sorry, mine was being caused by another gem. Updating to the latest version of Rails 5 beta on master showed which gem it was coming from.

**Comment by samphippen** [comment] 2016-04-02 15:35
@gregblass we can close this right?

**Comment by gregblass** [comment] 2016-04-02 21:13
For my case it was definitely not coming from rspec-rails. Not sure if this was the same case for the person that opened this. I'd bet it was.

**Comment by connorshea** [comment] 2016-04-02 21:45
I vote to close, as I would assume based on @gregblass's comments it's not an Rspec issue.

**Closed** 2016-04-02 22:18 UTC

**Comment by jbhatab** [comment] 2016-04-24 12:24
My code keeps yelling at me that it's this line,

```
require 'rspec/rails'
```

![screen shot 2016-04-24 at 7 24 14 am](https://cloud.githubusercontent.com/assets/2458718/14767538/97beda40-09ed-11e6-953a-feec995497eb.png)

Just normal beta stuff, but thought I'd post this up.

**Comment by samphippen** [comment] 2016-04-24 12:45
I just grepped. As far as I can tell RSpec rails does not use before_filter or after_filter anywhere:

```
(master)$ git grep -i "before_filter"
(master)$ git grep -i "after_filter"
(master)$
```

**Comment by JonRowe** [comment] 2016-04-24 23:25
We don't, this is most likely a 3rd party gem as above...

**Comment by jbhatab** [comment] 2016-04-25 01:46
So weird. I wonder why it's saying the require 'rspec/rails' line is the problem line?

**Comment by JonRowe** [comment] 2016-04-25 02:31
Backtrace filtering
>
>

**Comment by jbhatab** [comment] 2016-04-25 03:52
@JonRowe which gem is this?

**Comment by JonRowe** [comment] 2016-04-25 04:43
*shrug* I'd check any which integrate with rails, grep through your gem folder for `before_filter` or `after_filter`

**Comment by daya** [comment] 2016-05-28 19:40
lucky me

```
ack before_filter /Users/dayas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/
```
shows
```
/Users/dayas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/turbolinks-2.5.3/lib/turbolinks.rb
14:          before_filter :set_xhr_redirected_to, :set_request_method_cookie
```
and removing turbolinks gem removes the deprecation warnings

**Comment by spickermann** [comment] 2016-05-28 20:19
@daya : [turbolinks `5.0.0.beta`](https://rubygems.org/gems/turbolinks) is already available. You might want to test your app against the version with:

    gem 'turbolinks', '~> 5.x'

**Comment by thomasbiddle** [comment] 2016-07-19 16:34
Upgrading turbolinks was the answer for me as well.
