### ISSUE TITLE
Post Request Body behaviour differ between RSpec-Rails and Real-Life 

### ISSUE THREAD

**Issue by martinBlacklane** [rspec/rspec-rails#2650] opened 2023-01-05 10:54 UTC
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 3.1.2
Rails version: 7.0.4
RSpec version: 3.12.0
RSpec-Rails version: 6.0.1

### Controller with POST route and body: 
  def query_insurances
    binding.pry
    params.require(:definition)
    render json: { results: [] }, status: :ok
  end

### Controller Spec: 
    describe "POST query_insurances with set but blank corporation" do
      subject {
        post :query_insurances, body: { definition: { corporation_id: "", currency: "EUR" } }
      }

      it "responds with 200 ok" do
        subject
        is_expected.to be_ok
      end
    end

## Observed behaviour
[2] pry(#<InsurancesController>)> params[:definition]
=> nil
[3] pry(#<InsurancesController>)> params["definition"]
=> nil
[4] pry(#<InsurancesController>)> JSON.parse(request.body.string)["definition"]
=> {"corporation_id"=>"", currency: "EUR"}

## Expected behaviour
[2] pry(#<InsurancesController>)> params[:definition]
=>  {"corporation_id"=>"", currency: "EUR"}
[3] pry(#<InsurancesController>)> params["definition"]
=>  {"corporation_id"=>"", currency: "EUR"}

This expected behaviour works if the route is called by curl or any other REST client. 

This behaviour was already reported here: https://github.com/rspec/rspec-rails/issues/2080
That bug was closed as duplicate, but not linked to the original issue. I'm using latest versions of Rails and RSpec-Rails, so i would expect this to work. 

Thanks a lot, 
Martin

**Comment by JonRowe** [comment] 2023-01-06 08:57
Closing as a duplicate of #2080 the advice there applies here, check how Rails wishes you to use `post` in their docs, its not RSpec functionality I'm afraid.

**Closed by JonRowe** 2023-01-06 08:57 UTC
