### ISSUE TITLE
be_succes(not be_success) passes in my tests.

### ISSUE THREAD

**Issue by adrianmann** [rspec/rspec-rails#1681] opened 2016-07-27 11:02 UTC
I noticed in one of my tests that I had a typo for the response check, `expect(response).to be_succes` instead of `expect(response).to be_success`. The test passed. I have tested this in other test files for `to` and `not_to` and I still get a pass. Why did the test still pass?

**Comment by JonRowe** [comment] 2016-07-27 12:01
`be_success` leverages the fact that `response` exposes a `success?` method, if `be_succes` also works then it's likely that `response` responds to `succes?` as well, although I can't find a citation for that at the moment.

Closing because unless I'm mistaken this is just a query and not a bug report :)

**Comment by adrianmann** [comment] 2016-07-27 12:28
`response.succes?` returns:

```
Failure/Error: response.succes?
     NoMethodError:
       undefined method `succes?' for #<ActionController::TestResponse:0x007fe6e22a2530>
```

It was kind of a "is this a bug" query :). I couldn't find an documentation either.

**Comment by samphippen** [comment] 2016-07-27 14:54
`succes` should probably be `success` right?

**Comment by adrianmann** [comment] 2016-07-27 14:56
Hi @samphippen, it should have been but I made a typo on my code. When I ran the tests, they still passed with the typo. Any instances that you see in this thread of `succes` were intentional.

**Comment by JonRowe** [comment] 2016-07-27 23:05
Can you copy and paste you exact spec? If response doesn't respond to `succes?` then `be_succes` should raise an error about response not responding to that method name.

**Comment by adrianmann** [comment] 2016-07-28 09:51
I can't post the exact code, here is a sample:

   ```
 it "creates this thing" do
    get :create_this_thing, study_id: study.friendly_id, user_id: user.id
    expect(response).to be_succes
    expect(flash[:success]).to eq("Successfully created this thing.")
  end
```

Again, `expect(response).to be_succes` does not cause an error. If I try something like `expect(response).to be_succ` or `expect(response).to be_successssss` then I do get an error such as:
```

Failure/Error: expect(response).to be_succ
       expected #<ActionController::TestResponse:0x007ffa67272400> to respond to `succ?`
```

and:

```
Failure/Error: expect(response).to be_successsss
       expected #<ActionController::TestResponse:0x007ffa67272400> to respond to `successsss?`
```

Again `response.success?` is fine but `response.succes?` returns:
```

Failure/Error: response.succes?
     NoMethodError:
       undefined method `succes?' for #<ActionController::TestResponse:0x007fe6e22a2530>
```

**Comment by JonRowe** [comment] 2016-07-28 11:09
What does `response.respond_to? :succes?` return? Or for that matter `response.methods.grep /succes/` (sorry to be a pain but I don't have a working rspec-rails project at the moment, all mine use plain RSpec)

**Comment by samphippen** [comment] 2016-07-28 11:18
the problem here is that we also allow present tense predicates e.g. `be_friends?` for a method called `friend?`

https://github.com/rspec/rspec-expectations/blob/master/lib/rspec/matchers/built_in/be.rb#L248

this is an intentional behaviour of RSpec and not a bug.

**Closed by samphippen** 2016-07-28 11:18 UTC

**Comment by JonRowe** [comment] 2016-07-28 11:21
I'm actually surprised by that.

**Comment by samphippen** [comment] 2016-07-28 11:22
It's a behaviour that I've often noted isn't to my personal preference, but it is intentional.

**Comment by JonRowe** [comment] 2016-07-28 11:25
Yeah I guess I've never needed: `be_friend` for `friends?` many other grammatial things but never that.

**Comment by adrianmann** [comment] 2016-07-28 11:34
:thumbsup: Thanks guys.

**Comment by myronmarston** [comment] 2016-07-28 14:37
> It's a behaviour that I've often noted isn't to my personal preference, but it is intentional.

Nor mine.  I don't think I've ever seen it used and I never really understood why we support that.  I think we should remove support in RSpec 4.  See rspec/rspec-expectations#935.
