### ISSUE TITLE
run all when everything filtered appears broken

### ISSUE THREAD

**Issue by goelinsights** [rspec/rspec-rails#1816] opened 2017-05-13 01:41 UTC
I created a new Rails 5.0.3 app and installed rspec-rails (latest)

followed the documentation for rspec 3.6 but was getting 0 of 0 examples run

Realized later that default run options were on calling rspec spec in the command line were: 
Run options:
  include {:focus=>true}
  exclude {:slow=>true}

And so silently, since none of the automatically created tests had :focus => true, they were all skipped.

This appears to be a) either a broken feature to run all when all tests are filtered or b) a documentation issue.

Any thoughts?  Also, is there a way to turn off the default configuration of 
    config.filter_run :focus => true

**Comment by JonRowe** [comment] 2017-05-17 12:46
What documentation did you follow? The suggested / auto generated configuration is `config.filter_run_when_matching :focus` which behaves differently to `config.filter_run :focus => true`

**Comment by JonRowe** [comment] 2017-05-18 10:22
Closing as this is the intended behaviour.

**Closed by JonRowe** 2017-05-18 10:22 UTC

**Comment by goelinsights** [comment] 2017-06-29 02:05
Realized I was missing this from rails_helper following an upgrade in versions:

  # These two settings work together to allow you to limit a spec run
  # to individual examples or groups you care about by tagging them with
  # `:focus` metadata. When nothing is tagged with `:focus`, all examples
  # get run.
  config.filter_run :focus
  config.run_all_when_everything_filtered = true
