### ISSUE TITLE
Relishapp Rspec Down?

### ISSUE THREAD

**Issue by markoj3s** [rspec/rspec-rails#2607] opened 2022-06-13 11:26 UTC
Hi,

I am trying to access Rspec's documentation but when I'm trying to access https://relishapp.com/rspec/ I am getting "404 - File or directory not found.".

**Comment by pirj** [comment] 2022-06-13 11:38
Thanks for reporting.
This is a duplicate of [this issue](https://github.com/rspec/rspec-metagem/issues/70).
I'll close this one, and let's discuss there.

**Closed by pirj** 2022-06-13 11:38 UTC

**Comment by markoj3s** [comment] 2022-06-13 16:14
Thank you for the quick reply @pirj !
Sorry, I tried to search for an existing issue but couldn't find it. Thanks for sharing!
