### ISSUE TITLE
suggested config causes suite to run twice

### ISSUE THREAD

**Issue by lazylester** [rspec/rspec-rails#2169] opened 2019-09-03 19:14 UTC
Ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
Rails 5.2.3
RSpec 3.8
  - rspec-core 3.8.2
  - rspec-expectations 3.8.4
  - rspec-mocks 3.8.1
  - rspec-rails 3.8.2
  - rspec-support 3.8.2

## Observed behaviour

Suggested config for Gemfile is to include rspec-rails in development and test groups (ref. README)
````ruby
#Gemfile
group :development, :test do
  gem 'rspec-rails'
end
````

Define `spec` as the default rake task in Rakefile, with a pattern specified for included `_spec.rb` files.

````ruby
# Rakefile
require "rspec/core/rake_task"
require_relative 'config/application'

Rails.application.load_tasks


RSpec::Core::RakeTask.new(:spec)

desc "run the entire test suite except request specs"
task :default => :spec
RSpec::Core::RakeTask.module_eval do
  def pattern
    "spec/models/**/*_spec.rb"
  end
end
````

Invoke the suite with `rake` no args, so default task invoked.

Test suite is executed twice. But when suggested Gemfile config is changed so that `rspec-rails` is included only in the test group. The suite is run once. I'm not sure if the README needs to be changed, or if `rspec-rails` needs to be changed. Or maybe this is intentional? It doesn't seem to be documented anywhere. There are numerous questions on SO about this, but apparently no-one has brought it to the attention of the awesome rspec devs (that I have found anyway).

## Expected behaviour

should execute all tests in the suite once.

## Can you provide an example app?

https://github.com/lazylester/rspec_test

ps. thanks for Rspec, I use it every day

**Comment by benoittgt** [comment] 2019-09-04 05:59
Hello

This is a duplicate of https://github.com/rspec/rspec-rails/issues/904#issuecomment-31512632

Feel free to comment on the other issue if you didn't find your answer.

**Closed by benoittgt** 2019-09-04 05:59 UTC

**Comment by benoittgt** [comment] 2019-09-04 06:07
In your case.

The issue is here:

https://github.com/lazylester/rspec_test/blob/master/Rakefile#L10-L18

You can remove this block.

**Comment by JonRowe** [comment] 2019-09-04 12:00
Incidentally there is a pattern option for the rake task, you don't (and shouldn't) monkey patch our task.

**Comment by JonRowe** [comment] 2019-09-05 13:37
As per #904 you are getting two specs because there are two spec tasks defined.

The TL;DR is define any overrides like this:
```Ruby
namespace :spec do
  RSpec::Core::RakeTask.new(:spec) do |task|
     task.pattern = "your_pattern"
  end
end
```

The longer explanation is that RSpec Rails automatically defines a task called "spec" within a namespace "spec" and then sets the default task for the namespace to be task, so `rake spec` is a shorthand for `rake spec:spec`. Just as `rake` is a shorthand for `rake spec` when you define `spec` to be the default task. So when you define another task called spec, there are now two tasks, `spec:spec` and `spec` triggered by `rake spec, and rake can't decide between them so runs both and if you followed that congratulations because I got confused just writing that 😂
