### ISSUE TITLE
Rails 5: uninitialized constant ActionView::Template::Handlers::ERB::ENCODING_FLAG

### ISSUE THREAD

**Issue by pmontrasio** [rspec/rspec-rails#1690] opened 2016-08-09 08:52 UTC
I have the `rails_helper.rb` and the `spec_helper.rb` generated by the scaffolder. I have an empty controller test

```
require 'rails_helper'

RSpec.describe HomeController, type: :controller do
end
```

When I run either `bundle exec rails spec` or `bundle exec rspec spec/controllers/home_controller_spec.rb` I get 

```
/home/me/.rvm/gems/ruby-2.3.1@global/gems/actionview-5.0.0/lib/action_view/template/handlers/erb.rb:90:in `<class:ERB>': uninitialized constant ActionView::Template::Handlers::ERB::ENCODING_FLAG (NameError)
Did you mean?  Encoding
    from /home/me/.rvm/gems/ruby-2.3.1@global/gems/actionview-5.0.0/lib/action_view/template/handlers/erb.rb:76:in `<module:Handlers>'
    from /home/me/.rvm/gems/ruby-2.3.1@global/gems/actionview-5.0.0/lib/action_view/template/handlers/erb.rb:5:in `<class:Template>'
    from /home/me/.rvm/gems/ruby-2.3.1@global/gems/actionview-5.0.0/lib/action_view/template/handlers/erb.rb:4:in `<module:ActionView>'
    from /home/me/.rvm/gems/ruby-2.3.1@global/gems/actionview-5.0.0/lib/action_view/template/handlers/erb.rb:3:in `<top (required)>'
    from /home/me/.rvm/gems/ruby-2.3.1@global/gems/actionview-5.0.0/lib/action_view/template/handlers.rb:12:in `require'
    from /home/me/.rvm/gems/ruby-2.3.1@global/gems/actionview-5.0.0/lib/action_view/template/handlers.rb:12:in `extended'
    from /home/me/.rvm/gems/ruby-2.3.1@global/gems/actionview-5.0.0/lib/action_view/template.rb:111:in `extend'
    from /home/me/.rvm/gems/ruby-2.3.1@global/gems/actionview-5.0.0/lib/action_view/template.rb:111:in `<class:Template>'
    from /home/me/.rvm/gems/ruby-2.3.1@global/gems/actionview-5.0.0/lib/action_view/template.rb:7:in `<module:ActionView>'
    from /home/me/.rvm/gems/ruby-2.3.1@global/gems/actionview-5.0.0/lib/action_view/template.rb:5:in `<top (required)>'
    from /home/me/.rvm/gems/ruby-2.3.1@global/gems/actionview-5.0.0/lib/action_view/template/resolver.rb:4:in `require'
    from /home/me/.rvm/gems/ruby-2.3.1@global/gems/actionview-5.0.0/lib/action_view/template/resolver.rb:4:in `<top (required)>'
    from /home/me/.rvm/gems/ruby-2.3.1@global/gems/actionview-5.0.0/lib/action_view/testing/resolvers.rb:1:in `require'
    from /home/me/.rvm/gems/ruby-2.3.1@global/gems/actionview-5.0.0/lib/action_view/testing/resolvers.rb:1:in `<top (required)>'
    from /home/me/.rvm/gems/ruby-2.3.1@my_app/gems/rspec-rails-3.5.1/lib/rspec/rails/view_rendering.rb:1:in `require'
    from /home/me/.rvm/gems/ruby-2.3.1@my_app/gems/rspec-rails-3.5.1/lib/rspec/rails/view_rendering.rb:1:in `<top (required)>'
    from /home/me/.rvm/gems/ruby-2.3.1@my_app/gems/rspec-rails-3.5.1/lib/rspec/rails.rb:9:in `require'
    from /home/me/.rvm/gems/ruby-2.3.1@my_app/gems/rspec-rails-3.5.1/lib/rspec/rails.rb:9:in `<top (required)>'
    from /home/me/my_app/my_app-web/spec/rails_helper.rb:2:in `require'
    from /home/me/my_app/my_app-web/spec/rails_helper.rb:2:in `<top (required)>'
    from /home/me/my_app/my_app-web/spec/controllers/home_controller_spec.rb:1:in `require'
    from /home/me/my_app/my_app-web/spec/controllers/home_controller_spec.rb:1:in `<top (required)>'
    from /home/me/.rvm/gems/ruby-2.3.1@my_app/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1435:in `load'
    from /home/me/.rvm/gems/ruby-2.3.1@my_app/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
    from /home/me/.rvm/gems/ruby-2.3.1@my_app/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1433:in `each'
    from /home/me/.rvm/gems/ruby-2.3.1@my_app/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
    from /home/me/.rvm/gems/ruby-2.3.1@my_app/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:100:in `setup'
    from /home/me/.rvm/gems/ruby-2.3.1@my_app/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:86:in `run'
    from /home/me/.rvm/gems/ruby-2.3.1@my_app/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:71:in `run'
    from /home/me/.rvm/gems/ruby-2.3.1@my_app/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:45:in `invoke'
    from /home/me/.rvm/gems/ruby-2.3.1@my_app/gems/rspec-core-3.5.2/exe/rspec:4:in `<top (required)>'
    from /home/me/.rvm/gems/ruby-2.3.1@my_app/bin/rspec:23:in `load'
    from /home/me/.rvm/gems/ruby-2.3.1@my_app/bin/rspec:23:in `<main>'
    from /home/me/.rvm/gems/ruby-2.3.1@my_app/bin/ruby_executable_hooks:15:in `eval'
    from /home/me/.rvm/gems/ruby-2.3.1@my_app/bin/ruby_executable_hooks:15:in `<main>'
```

The workaround is to add `require "rails/all"` at the beginning of `rails_helper.rb` or of `spec_helper.rb` but that wasn't needed for Rails 4 and rspec-rails 3.1. 

Did I miss something in the documentation?

**Comment by JonRowe** [comment] 2016-08-09 09:23
Are you using Rails api?

**Comment by pmontrasio** [comment] 2016-08-09 15:30
No, it's normal Rails and ERB is loaded: the views work.

**Comment by pmontrasio** [comment] 2016-08-09 15:35
I've been googling and experimenting. I can workaround the problem by adding either of these two lines to ```spec_helper.rb```

```
require "active_record/railtie"
require "action_controller/railtie"
```

One of them is enough, it doesn't matter which one.
I found a reference to them at http://stackoverflow.com/questions/32916766/why-is-require-rails-all-not-installed-required-in-my-config-application-rb

**Comment by pmontrasio** [comment] 2016-08-09 15:42
I created the application with ```rails new my_app ---skip-bundle -skip-test```, added rspec-rails 3.5 to the Gemfile and run ```bundle install``` plus ```rails generate rspec:install```. Did ```--skip-test``` omitted some initialization file that rspec relies on?

**Comment by JonRowe** [comment] 2016-08-10 03:29
Whats in your `config/environment.rb` we load that to load rails so if you're missing pieces in there...

**Comment by pmontrasio** [comment] 2016-08-10 08:03
It's the one generated by Rails.

```
require_relative 'boot'

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "action_cable/engine"
require "sprockets/railtie"
#require "rails/test_unit/railtie"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module MyApp
  class Application < Rails::Application
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.
  end
end
```

The line ```#require "rails/test_unit/railtie"``` is commented, probably because of the ```--skip-test```.
I uncommented it but I still get the error.

It's strange that I have to re-require that ```active_record/railtie``` or ```action_controller/railtie``` again in the spec helpers. I'll find out what happened the next time I'll create a new application from scratch. I can live with requiring those files in the helper and if I'll get some more error maybe it will hint to the solution.

**Comment by samphippen** [comment] 2016-08-10 18:15
Hi @pmontrasio 

Thanks for the issue. We need a little more detail to be able to reproduce this.

Could you please provide us with a rails app that we can clone that demonstrates the issue. Specifically it'd be great if

1)  you could `rails new` an application and commit
2) make all the changes necessary to reproduce the issue and commit

then, provide us with a description of how to clone your application and reproduce the issue.

Thanks :)

**Comment by nickrobinson** [comment] 2016-11-27 16:15
Attempted to reproduce in https://github.com/nickrobinson/nickrobinson-rspec_rails_issue_1690/commit/e587eb1c38529aff898c5b13aa6beee03cfb589d following the @pmontrasio info with no luck. Using Rails 5.0 and rspec-rails 3.5.2

**Comment by jaysonbucy** [comment] 2017-02-02 01:31
@samphippen I have the same error
https://github.com/jaysonbucy/blocipedia/tree/checkpoint-2

**Comment by terratakashi** [comment] 2017-02-15 18:13
I got the same issue, but after I adding `require File.expand_path(\"../../config/environment\", __FILE__)` to my `spec_help.rb`, and it works.

**Comment by jasonfb** [comment] 2017-03-29 14:15
we saw this error on a brand new Rails 4.2.5 app; on my colleague's machine @collinschendier (he is running Mac OS X El Capitan), the app does *not* display this symptom, and runs fine.

When I pulled the repository on my machine (also running OS X El Capitan) I get ```uninitialized constant ActionView::Template::Handlers::ERB::ENCODING_FLAG (NameError)``` when I run ```bundle exec rspec```

I tried on another machine running Mac OS Sierra and got the same result.

**Comment by jasonfb** [comment] 2017-03-29 14:21
see http://stackoverflow.com/questions/4429068/getting-an-unitialized-constant-error-with-rspec-have-no-idea-whats-causing-it

I got around this by adding to my spec_helper.rb file
```
require File.expand_path("../../config/environment", __FILE__)
```

**Comment by sc0ttman** [comment] 2017-04-13 18:31
I have a Rails5 app using `rspec-rails` and added the includes to `rails_helper.rb` instead of `spec_helper.rb` and it worked fine for me.

**Comment by amh22** [comment] 2017-05-19 02:07
Am running a Rails 5 app and came across the same problem. In `spec_helper.rb` I needed to do both:

add: `require File.expand_path('../../config/environment', __FILE__)`

and replace `require 'rspec/rails'

with `require 'rails/all'

**Comment by LauraKirby** [comment] 2017-06-02 21:48
I came across this problem as well when creating a new Rails 5.1.1. app, with Rspec, Capybara and Factory Girl. Things worked once I placed **expand_path** at the top of the file. 

My setup looks like: 
```
require File.expand_path("../../config/environment", __FILE__)
require 'rails/all'
require 'capybara/rails'
require 'factory_girl_rails'
```

**Comment by JonRowe** [comment] 2017-06-05 03:46
Be aware that adding `require File.expand_path('../../config/environment', __FILE__)` causes rails to be booted essentially so should only be added to files where thats expected to be the case (which is not normally needed for plain old ruby specs).

**Comment by aubreywahl** [comment] 2017-06-27 17:39
I fixed this (on a fresh Rails 5 app, haven't even added test yet) by changing the .rspec file from 

`--require spec_helper`

to

`--require rails_helper`

Does this seem ok to ppl?

**Comment by JonRowe** [comment] 2017-06-27 23:19
@aubreywahl no that eliminates the advantages of the split test helpers (so you might as well only have one) and makes rails always boot

**Comment by HeidiHansen** [comment] 2017-08-31 20:44
@jasonfb, your solution worked for me, finally.  Thank you =)

**Comment by durhamka** [comment] 2018-04-25 01:41
@samphippen Old issue, but I have a student that is running into this issue. Tried all of the suggestions above. She is on the latest version of RSpec and Rails 5.1.6. Were you ever able to figure out the issue or resolve? Thank you for all the work you do on this gem and don't want to add more work to your plate :) lol

**Comment by joshwcorbett** [comment] 2019-11-19 03:44
I seem to not have a rails_spec file, and when I try to generate one rails gives me the same error!

**Comment by jasonfb** [comment] 2019-11-19 12:50
@joshwcorbett -- did you add the the require for the environment in the spec_helper file?

if it can't load the Rails environment it won't be able to load the generators

see https://stackoverflow.com/questions/4429068/getting-an-uninitialized-constant-error-with-rspec-have-no-idea-whats-causing

**Comment by pirj** [comment] 2020-03-20 23:28
> did you add the require for the environment in the spec_helper file?

Normally you shouldn't be doing that. `spec/rails_helper.rb` needs this line, and the [default generator puts it there](https://github.com/rspec/rspec-rails/blob/master/lib/generators/rspec/install/templates/spec/rails_helper.rb#L4).

> if it can't load the Rails environment it won't be able to load the generators

`rails generate` should be loading some files, but why would it have to load `spec_helper.rb?
I hope you've added `rspec-rails` to both `:test` and `:development` groups as [`README` suggests](https://github.com/rspec/rspec-rails#installation)

It seems that some kind of common misconfiguration is causing this problem. However, since reproduction example was not provided and it's been recommended several times to load full Rails env from `spec_helper.rb`, which we strongly don't recommend, I'm more inclined to close this until there's a clear case that can be researched and fixed as needed.

**Comment by pirj** [comment] 2020-04-03 09:18
Closing as there's no clear reproduction case.

**Comment by johnpitchko** [comment] 2021-07-22 10:41
I encountered this error when I added `require 'rspec/rails'` in my `spec_helper.rb` (as advised in the Devise README) but I did not realize that this line already existed in `rails_helper.rb`.

**Comment by pirj** [comment] 2021-07-22 11:43
Interesting! Thanks for the heads-up, @johnpitchko

**Comment by cjguarino** [comment] 2022-02-04 14:47
I had this same problem and fixed it by moving my environment file before I require rspec in my rails_helper.rb:

````
ENV["RAILS_ENV"] ||= 'test'
require File.expand_path("../../links_engine_RSPEC/config/environment.rb", __FILE__)

require 'capistrano'
require 'rspec/rails' 
````

**Comment by gaultierq** [comment] 2022-11-12 14:23
in my `.rspec` , having `--require rails_helper` before `--require spec_helper` fixed the issue

**Comment by JonRowe** [comment] 2022-11-12 21:17
(Closing because Rails 5 is no longer supported)

**Closed** 2022-11-12 21:17 UTC
Labels: Needs reproduction case
