### ISSUE TITLE
ActiveJob `have_enqueued_job.with` cannot match objects

### ISSUE THREAD

**Issue by ssuttner** [rspec/rspec-rails#1528] opened 2016-01-15 17:32 UTC
Hey, 

I'm having trouble using the `.with` method.
It works ok with simple arguments such as strings or integers, but it does not for model instances.

I debugged the code and on this line
https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/matchers/active_job.rb#L29

it checks that the serialized argument matches the argument of the job, and that second one is not serialized.
It kind of ends up comparing `{"_aj_globalid"=>"gid://app/user/1"}` with `#<User:0x007ffcef216530>` ,which will never be true.

Am I doing something wrong, or is this something that needs to be fixed?
Please help me figure that out.
Thanks!

**Comment by JonRowe** [comment] 2016-01-17 22:33
Thats kinda expected, ActiveJob will only queue simple arguments like strings and integers, as you can see it automatically serialises the model to it's global id, if you checked for the presence of the global id in the queue it'd work fine. If you'd like to work up a PR for us automatically translating arguments into their global id I think I'd support it.

**Comment by morgoth** [comment] 2016-01-30 09:35
@ssuttner If I understand your issue correctly, it should work. Take a look at this spec https://github.com/rspec/rspec-rails/blob/master/spec/rspec/rails/matchers/active_job_spec.rb#L192-L198
Global ID object is serialized as a job argument as well as an argument for `with` method.

**Comment by JonRowe** [comment] 2016-01-31 00:20
Hmm, interesting

**Comment by samphippen** [comment] 2016-02-13 14:43
@ssuttner does this issue still affect you?

**Comment by bolshakov** [comment] 2016-07-06 13:29
This problem happens when you use rspec-rails with ActiveJob version less then 4.2.1.

The problem described here: https://github.com/gocardless/rspec-activejob

> rspec-activejob expects the current queue adapter to expose an array of enqueued_jobs, like the included test adapter. The test adapter included in ActiveJob 4.2.0 does not fully serialize its arguments, so you will not need to use the GlobalID matcher unless you're using ActiveJob 4.2.1. See rails/rails#18266 for the improved test adapter.

**Comment by samphippen** [comment] 2016-07-08 14:23
This works for me with a simple activerecord base object. @ssuttner 
Thanks for the issue. We need a little more detail to be able to reproduce this.

Could you please provide us with a rails app that we can clone that demonstrates the issue. Specifically it'd be great if

1)  you could `rails new` an application and commit
2) make all the changes necessary to reproduce the issue and commit

then, provide us with a description of how to clone your application and reproduce the issue.

Thanks :)

**Comment by samphippen** [comment] 2016-07-22 12:52
@ssuttner I'm going to close this because I struggled to reproduce. If you can provide us with a reproduction case, I'm happy to re-open and take a look.

**Closed by samphippen** 2016-07-22 12:52 UTC
Labels: Needs reproduction case
