### ISSUE TITLE
get transforms to post if params given

### ISSUE THREAD

**Issue by exocode** [rspec/rspec-rails#2502] opened 2021-05-23 09:40 UTC
## What Ruby, Rails and RSpec versions are you using?

Ruby version: `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]`
Rails version: `Rails 6.1.3.1`
RSpec version:

```
RSpec 3.10
  - rspec-core 3.10.1
  - rspec-expectations 3.10.1
  - rspec-mocks 3.10.2
  - rspec-rails 5.0.1
  - rspec-support 3.10.2
 ```

## Observed behaviour
routes.rb

`  get '/users/:id/billing_addresses', to: "billing_addresses#index"`

my spec.rb
```
 get "/users/#{user.id}/billing_addresses",
          params: { some_param: some_param }, # <---- transforms get request to a post request
          headers: valid_headers,
          as: :json
```
`Started POST "/users/2/billing_addresses" `

If I remove `params: { some_param: some_param }` like so:

```
 get "/users/#{user.id}/billing_addresses",
          headers: valid_headers,
          as: :json
```

it keeps a get request
``Started GET "/users/2/billing_addresses" ``

## Expected behaviour

```
 get "/users/#{user.id}/billing_addresses",
          headers: valid_headers,
          as: :json
```
should trigger 

`Started GET "/users/2/billing_addresses" `

**Comment by pirj** [comment] 2021-05-23 11:34
`get` is a Rails helper method. I suggest you to check with them.
GET requests semantically do not include body, and `as:` implies you're setting body's content type.
Do you mean to say "request JSON results"?

**Comment by benoittgt** [comment] 2021-05-23 18:23
Hello

Did you tried with the parameter as a hash? 

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "6.1.0"
  gem "rspec-rails"
end

require "rspec-rails"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: "Param : #{params["test"]}"
  end
end

require 'rspec/autorun'

RSpec.describe 'additions', type: :request do
  include Rack::Test::Methods

  let(:valid_headers) { { "Authorization" => "foo" } }

  it do
    get "/",
      { "test" => "Foo" },
      headers: valid_headers,
      as: :json
    expect(last_response.body).to include("Param : Foo")
  end

  private

  def app
    Rails.application
  end
end
```

**Comment by kucho** [comment] 2022-10-03 15:36
I was able to reproduce the issue with an identical code. What @pirj was saying is defined in [here](https://github.com/rails/rails/blob/433115554d3ea0b4dab9df99548c47707cadb20d/actionpack/lib/action_dispatch/testing/integration.rb#L215). 

I tried @benoittgt's script and it worked. However, I couldn't get my test passing. 

After checking line by line, I finally found it. Somehow this line `include Rack::Test::Methods` fixes my test case:

```
RSpec.describe "/movies", type: :request do
  include Rack::Test::Methods
  
  describe "GET /index" do
    it "returns the last page only" do
      Movie.create!(title: "Ignored Movie")
      batman_movie = Movie.create!(title: "Batman")
      get movies_url, params: {page: {size: 1, number: 2}}, as: :json
      movies = JSON.parse(response.body)["movies"]
      expect(movies.size).to eq 1
      expect(movies.last.title).to eq batman_movie.title
    end
  end
end
``` 

I'm running rspec main: 
```
  %w[rspec-core rspec-expectations rspec-mocks rspec-rails rspec-support].each do |lib|
    gem lib, git: "https://github.com/rspec/#{lib}.git", branch: "main"
  end
```

Here's my locked version:

```
GIT
  remote: https://github.com/rspec/rspec-core.git
  revision: 71823ba11ec17a73b25bdc24ebab195494c270dc
  branch: main
  specs:
    rspec-core (3.12.0.pre)
      rspec-support (= 3.12.0.pre)

GIT
  remote: https://github.com/rspec/rspec-expectations.git
  revision: 311aaf245f2c5493572bf683b8c441cb5f7e44c8
  branch: main
  specs:
    rspec-expectations (3.12.0.pre)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (= 3.12.0.pre)

GIT
  remote: https://github.com/rspec/rspec-mocks.git
  revision: 2c70bfbb5bc0f59525032615c8fa989dd1ade243
  branch: main
  specs:
    rspec-mocks (3.12.0.pre)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (= 3.12.0.pre)

GIT
  remote: https://github.com/rspec/rspec-rails.git
  revision: 6b4969ef8e20cbd21c51840c158b91f90630041c
  branch: main
  specs:
    rspec-rails (6.0.0.pre)
      actionpack (>= 6.1)
      activesupport (>= 6.1)
      railties (>= 6.1)
      rspec-core (= 3.12.0.pre)
      rspec-expectations (= 3.12.0.pre)
      rspec-mocks (= 3.12.0.pre)
      rspec-support (= 3.12.0.pre)

GIT
  remote: https://github.com/rspec/rspec-support.git
  revision: 5d653dfd130d45a742ab2300662b624e191f76a0
  branch: main
  specs:
    rspec-support (3.12.0.pre)
```

**Comment by kucho** [comment] 2022-10-03 16:19
I don't think it's a bug anymore. The explanation is here: https://github.com/rails/rails/commit/af1680f51c127c7e40019e68c01b2a693ba2640f. I think it could be more visible somehow. Anyways, after deleting the explicit `as: :json` everything is back to normal.

**Comment by JonRowe** [comment] 2022-10-10 16:36
Closing as this seems the intended behaviour on Rails end.

**Closed** 2022-10-10 16:36 UTC
