### ISSUE TITLE
Rspec test suite stops in random moments without any error/warning/info

### ISSUE THREAD

**Issue by panSarin** [rspec/rspec-rails#1363] opened 2015-05-06 13:40 UTC
my test:

```
feature 'Endow policy', 'In order to
set nnw ace5 endow,
, i want to', js: true do
  before :each do
    @agent = sign_in_as('agent')
  end

  context 'creating endow from financing' do
    it 'valid case' do
      @calc = create(:calculation, user: @agent, status: '10', manager: @agent)
      visit edit_calculation_path(@calc')
      find("#collapser_rest_informations").click
      fill_in 'Some field (%)', with: 20
      find("#collapser_rest_informations").click
      click_on 'Zapisz'
      page.should have_content('Calculation updated')
    end
  end
```

after i run it sometimes i get

```
ap@ap-sat:~/projects/my_project$ rspec spec/acceptance//endow_spec.rb

Endow policy In order to
set nnw ace5 endow,
, i want to
  creating endow from financing
ap@ap-sat:~/projects/NAU$
```
and sometimes i get passed test. How can i find the reason? I debugged what i could but have no more idea.

I`m sure that my ajax requests that are issue, but can't figure out how and when. 
Any tips how to debug it or get more informations why test stop without any error?

**Comment by JonRowe** [comment] 2015-05-06 22:24
That's not a normal RSpec exit condition, it's possible that something else is forcing an exit from your code and overriding RSpecs interrupt but it's still pretty odd, whats the exit status in that scenario? And what driver are you using for capybara?

**Comment by panSarin** [comment] 2015-05-07 09:19
I tested it on capybara-webkit and selenium and on both i have that issue. But it is more often if i run 10 tests at once than if i run single test. Is there any tool to monitor ram/cpu usage by ruby process in each line of test?

**Comment by JonRowe** [comment] 2015-05-07 11:25
Not specifically, but if Ruby had crashed you would have received a backtrace / stack frames. It's more likely something is forcing an exit.

**Comment by panSarin** [comment] 2015-05-08 08:57
ok , thx . At least i have idea what kind of tools i should use to track it ;]

**Comment by samphippen** [comment] 2015-11-29 23:08
@panSarin I think this is unlikely to be an RSpec specific issue. That said, if you can build a simple reproduction case, we'll happily debug it. Can you provide a url to a git repo which contains a rails app that contains two commits:

* First commit is just the result of `rails g mytestapp`
* Second commit is all the changes necessary to reproduce this bug.

Then, give us some commands to run or similar to show the bug appearing. We're happy to help you fix this, but we need to be able to reproduce this first. :smile:

**Comment by samphippen** [comment] 2015-12-01 16:03
I'm going to close this because we don't have a reproduction case. @panSarin If you can provide one we'll hapilly re-open and investigate.

**Closed by samphippen** 2015-12-01 16:03 UTC
Labels: Needs reproduction case
