### ISSUE TITLE
be_a_new(Record) or be_new_record they are both private API's which one is the correct one to use?

### ISSUE THREAD

**Issue by staycreativedesign** [rspec/rspec-rails#1413] opened 2015-07-03 20:56 UTC
http://www.rubydoc.info/gems/rspec-rails/RSpec/Rails/Matchers/BeANew

http://www.rubydoc.info/gems/rspec-rails/RSpec/Rails/Matchers#be_new_record-instance_method

**Comment by cupakromer** [comment] 2015-07-03 21:42
:blue_heart: thanks for reporting this.

This seems to be an issue with how Yard is parsing our files. The classes are private but the helper methods [`be_a_new(model_class)`](http://www.rubydoc.info/gems/rspec-rails/RSpec/Rails/Matchers#be_a_new-instance_method) and [`be_new_record`](http://www.rubydoc.info/gems/rspec-rails/RSpec/Rails/Matchers#be_new_record-instance_method) should be public. I'm looking into what is up with our Yard docs that could be causing this.

**Comment by staycreativedesign** [comment] 2015-07-03 21:50
Yay I'm glad I can help :) my first doc help ever

**Comment by cupakromer** [comment] 2015-07-03 21:58
Happy to accept a PR for this! :smile_cat: I don't have an obvious suggestion at this time. Those methods don't appear to be marked "private", so I'm un-sure off the top of my head what the cause may be.

My initial thoughts:

- maybe just adding `@public` would help
- :bug: in Yard (or our version which we could bump)
- move / copy docs or helpers into [`lib/rspec/rails/matchers.rb`](https://github.com/rspec/rspec-rails/blob/1fb6f9f642e887df1b1ee344594de02d7de3b3fe/lib/rspec/rails/matchers.rb) mirroring how [`rspec-expectations/lib/rspec/matchers.rb`](https://github.com/rspec/rspec-expectations/blob/1a362f1256c475c48315f6cb250434def53a54d7/lib/rspec/matchers.rb) does it

**Comment by myronmarston** [comment] 2015-07-04 05:49
I always run `bin/yard server --reload` and view the rendered docs while editing them.  I don't have any suggestions for what the specific fix should be but that'll give whoever works on a fix for this an easy way to verify they have in fact fixed it.

**Comment by JonRowe** [comment] 2015-08-07 18:53
The authoritative source for our docs is not `rdoc.info`, but `http://rspec.info/documentation`, `be_a_new` renders ok there.

**Closed** 2015-08-07 18:53 UTC
Labels: small
